// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/domainpb/dns_record.proto

package domainpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DNSRecordType int32

const (
	DNSRecordType_RECORD_UNKNOWN DNSRecordType = 0
	// Type id 1, RFC 1035. Address record. Returns a 32-bit IPv4 address; most
	// commonly used to map hostnames to an IP address, but also used for DNSBLs,
	// storing subnet masks, etc.
	DNSRecordType_A DNSRecordType = 1
	// Type id 2, RFC 1035. Name server record. Delegates a DNS zone to use the
	// given authoritative name servers.
	DNSRecordType_NS DNSRecordType = 2
	// Type id 5, RFC 1035. Canonical name record. Alias of one name to another;
	// the DNS lookup will continue by retrying the lookup with the new name.
	DNSRecordType_CNAME DNSRecordType = 5
	// Type id 6, RFC 1035 / RFC 2308. Start of authority record. Specifies
	// authoritative information about a DNS zone, including the primary name
	// server, the email of the domain administrator, the domain serial number,
	// and several timers relating to refreshing the zone.
	DNSRecordType_SOA DNSRecordType = 6
	// Type id 12, RFC 1035. PTR resource record. Pointer to a canonical name.
	// Unlike a CNAME, DNS processing stops and just the name is returned. Most
	// commonly used for reverse DNS lookups, but also for things like DNS-SD.
	DNSRecordType_PTR DNSRecordType = 12
	// Type id 13, RFC 8482 / RFC 1035. Host information / placeholder record.
	// Originally intended to inform about a host's OS and hardware; repurposed
	// by RFC 8482 to be used while responding to ANY queries.
	DNSRecordType_HINFO DNSRecordType = 13
	// Type id 15, RFC 1035 / RFC 7505. Mail exchange record. List of mail
	// exchange servers that accept email for a domain.
	DNSRecordType_MX DNSRecordType = 15
	// Type id 16, RFC 1035. Text record. Originally for arbitrary human-readable
	// text; now more often carries machine-readable data such as SPF, DKIM,
	// DMARC, DNS-SD, opportunistic encryption, etc.
	DNSRecordType_TXT DNSRecordType = 16
	// Type id 17, RFC 1183. Responsible Person. Information about the
	// responsible person(s) for the domain. Usually an email address with the
	// @ replaced by a dot.
	DNSRecordType_RP DNSRecordType = 17
	// Type id 18, RFC 1183. AFS database record. Location of database servers
	// of an AFS cell. Used by AFS clients to contact AFS cells outside their
	// local domain. A subtype is used by the obsolete DCE/DFS file system.
	DNSRecordType_AFSDB DNSRecordType = 18
	// Type id 24, RFC 2535. Signature record. Used in SIG(0) (RFC 2931) and
	// TKEY (RFC 2930). RFC 3755 designated RRSIG as the replacement for SIG
	// for use within DNSSEC.
	DNSRecordType_SIG DNSRecordType = 24
	// Type id 25, RFC 2535 / RFC 2930. Key record. Used only for SIG(0) and
	// TKEY. RFC 3445 limited their use to DNSSEC; RFC 3755 designates DNSKEY
	// as the replacement within DNSSEC, and RFC 4025 designates IPSECKEY as
	// the replacement for use with IPsec.
	DNSRecordType_KEY DNSRecordType = 25
	// Type id 28, RFC 3596. IPv6 address record. Returns a 128-bit IPv6 address,
	// most commonly used to map hostnames to an IP address of the host.
	DNSRecordType_AAAA DNSRecordType = 28
	// Type id 29, RFC 1876. Location record. Specifies a geographical location
	// associated with a domain name.
	DNSRecordType_LOC DNSRecordType = 29
	// Type id 33, RFC 2782. Service locator. Generalized service location
	// record, used for newer protocols instead of creating protocol-specific
	// records such as MX.
	DNSRecordType_SRV DNSRecordType = 33
	// Type id 35, RFC 3403. Naming Authority Pointer. Allows regular-expression-
	// based rewriting of domain names which can then be used as URIs, further
	// domain names to lookups, etc.
	DNSRecordType_NAPTR DNSRecordType = 35
	// Type id 36, RFC 2230. Key Exchanger record. Used with some cryptographic
	// systems (not DNSSEC) to identify a key management agent for the
	// associated domain name. Informational status, limited deployment.
	DNSRecordType_KX DNSRecordType = 36
	// Type id 37, RFC 4398. Certificate record. Stores digital certificates in
	// various forms (PKIX, SPKI, PGP, etc.).
	DNSRecordType_CERT DNSRecordType = 37
	// Type id 39, RFC 6672. Delegation name record. Alias for a name and all
	// its subnames, unlike CNAME, which is an alias for only the exact name.
	// Like CNAME, the DNS lookup will continue by retrying with the new name.
	DNSRecordType_DNAME DNSRecordType = 39
	// Type id 41, RFC 6891. OPT pseudo-record needed to support EDNS.
	DNSRecordType_OPT DNSRecordType = 41
	// Type id 42, RFC 3123. Address Prefix List. Specifies lists of address
	// ranges, e.g. in CIDR format, for various address families. Experimental.
	DNSRecordType_APL DNSRecordType = 42
	// Type id 43, RFC 4034. Delegation signer. The record used to identify the
	// DNSSEC signing key of a delegated zone.
	DNSRecordType_DS DNSRecordType = 43
	// Type id 44, RFC 4255. SSH public key fingerprint. Resource record for
	// publishing SSH public host key fingerprints in DNS, to aid in verifying
	// host authenticity. RFC 6594 defines ECC SSH keys and SHA-256 hashes.
	DNSRecordType_SSHFP DNSRecordType = 44
	// Type id 45, RFC 4025. IPsec Key. Key record that can be used with IPsec.
	DNSRecordType_IPSECKEY DNSRecordType = 45
	// Type id 46, RFC 4034. DNSSEC signature for a record set. Uses the same
	// format as the SIG record.
	DNSRecordType_RRSIG DNSRecordType = 46
	// Type id 47, RFC 4034. Next Secure record. Part of DNSSEC—used to prove
	// a name does not exist. Uses the same format as the (obsolete) NXT record.
	DNSRecordType_NSEC DNSRecordType = 47
	// Type id 48, RFC 4034. DNS Key record used in DNSSEC. Uses the same
	// format as the KEY record.
	DNSRecordType_DNSKEY DNSRecordType = 48
	// Type id 49, RFC 4701. DHCP identifier. Used in conjunction with the FQDN
	// option to DHCP.
	DNSRecordType_DHCID DNSRecordType = 49
	// Type id 50, RFC 5155. Next Secure record version 3. An extension to
	// DNSSEC that allows proof of nonexistence for a name without permitting
	// zone walking.
	DNSRecordType_NSEC3 DNSRecordType = 50
	// Type id 51, RFC 5155. NSEC3 parameters. Parameter record for use with
	// NSEC3.
	DNSRecordType_NSEC3PARAM DNSRecordType = 51
	// Type id 52, RFC 6698. TLSA certificate association. A record for DANE,
	// used to associate a TLS server certificate or public key with the domain
	// name where the record is found.
	DNSRecordType_TLSA DNSRecordType = 52
	// Type id 53, RFC 8162. S/MIME certificate association. Associates an
	// S/MIME certificate with a domain name for sender authentication.
	DNSRecordType_SMIMEA DNSRecordType = 53
	// Type id 55, RFC 8005. Host Identity Protocol. Method of separating the
	// end-point identifier and locator roles of IP addresses.
	DNSRecordType_HIP DNSRecordType = 55
	// Type id 59, RFC 7344. Child DS. Child copy of DS record, for transfer
	// to parent.
	DNSRecordType_CDS DNSRecordType = 59
	// Type id 60, RFC 7344. Child copy of DNSKEY record, for transfer to
	// parent.
	DNSRecordType_CDNSKEY DNSRecordType = 60
	// Type id 61, RFC 7929. OpenPGP public key record. A DANE method for
	// publishing and locating OpenPGP public keys in DNS for a specific email
	// address.
	DNSRecordType_OPENPGPKEY DNSRecordType = 61
	// Type id 62, RFC 7477. Child-to-Parent Synchronization. Specifies a
	// synchronization mechanism between a child and a parent DNS zone, e.g.
	// declaring the same NS records in both zones.
	DNSRecordType_CSYNC DNSRecordType = 62
	// Type id 63, RFC 8976. Message Digests for DNS Zones. Provides a
	// cryptographic message digest over DNS zone data at rest.
	DNSRecordType_ZONEMD DNSRecordType = 63
	// Type id 64, RFC 9460. Service Binding. Provides metadata and other
	// information that can help clients connect to the host. The more general
	// SVCB record can convey supported protocols, alternative endpoints, and
	// some types of aliasing not supported by CNAME.
	DNSRecordType_SVCB DNSRecordType = 64
	// Type id 65, RFC 9460. HTTPS Binding. Specialised SVCB record providing
	// connection information for HTTPS, allowing more secure connections (e.g.
	// Encrypted Client Hello) and lower first-connection latency.
	DNSRecordType_HTTPS DNSRecordType = 65
	// Type id 108, RFC 7043. MAC address (EUI-48). A 48-bit IEEE Extended
	// Unique Identifier.
	DNSRecordType_EUI48 DNSRecordType = 108
	// Type id 109, RFC 7043. MAC address (EUI-64). A 64-bit IEEE Extended
	// Unique Identifier.
	DNSRecordType_EUI64 DNSRecordType = 109
	// Type id 249, RFC 2930. Transaction Key record. A method of providing
	// keying material to be used with TSIG that is encrypted under the public
	// key in an accompanying KEY RR.
	DNSRecordType_TKEY DNSRecordType = 249
	// Type id 250, RFC 2845. Transaction Signature. Can be used to authenticate
	// dynamic updates as coming from an approved client, or to authenticate
	// responses as coming from an approved recursive name server.
	DNSRecordType_TSIG DNSRecordType = 250
	// Type id 251, RFC 1996. Incremental Zone Transfer. Requests a zone
	// transfer of the given zone but only differences from a previous serial
	// number. May fall back to AXFR if deltas are unavailable.
	DNSRecordType_IXFR DNSRecordType = 251
	// Type id 252, RFC 1035. Authoritative Zone Transfer. Transfer entire zone
	// file from the primary name server to secondary name servers.
	DNSRecordType_AXFR DNSRecordType = 252
	// Type id 255, RFC 1035. All cached records (commonly referred to as ANY
	// or *). Returns all records of all types known to the name server. Since
	// RFC 8482, many providers (e.g. Cloudflare) return only minimal responses
	// to ANY queries instead of enumerating records.
	DNSRecordType_ANY DNSRecordType = 255
	// Type id 256, RFC 7553. Uniform Resource Identifier. Can be used for
	// publishing mappings from hostnames to URIs.
	DNSRecordType_URI DNSRecordType = 256
	// Type id 257, RFC 8659. Certification Authority Authorization. Constrains
	// acceptable CAs for a host/domain.
	DNSRecordType_CAA DNSRecordType = 257
	// Type id 32768, no RFC. DNSSEC Trust Authorities. Part of a deployment
	// proposal for DNSSEC without a signed DNS root. Uses the same format as
	// the DS record.
	DNSRecordType_TA DNSRecordType = 32768
	// Type id 32769, RFC 4431. DNSSEC Lookaside Validation record. For
	// publishing DNSSEC trust anchors outside of the DNS delegation chain.
	// Uses the same format as the DS record; RFC 5074 describes its use.
	DNSRecordType_DLV DNSRecordType = 32769
)

// Enum value maps for DNSRecordType.
var (
	DNSRecordType_name = map[int32]string{
		0:     "RECORD_UNKNOWN",
		1:     "A",
		2:     "NS",
		5:     "CNAME",
		6:     "SOA",
		12:    "PTR",
		13:    "HINFO",
		15:    "MX",
		16:    "TXT",
		17:    "RP",
		18:    "AFSDB",
		24:    "SIG",
		25:    "KEY",
		28:    "AAAA",
		29:    "LOC",
		33:    "SRV",
		35:    "NAPTR",
		36:    "KX",
		37:    "CERT",
		39:    "DNAME",
		41:    "OPT",
		42:    "APL",
		43:    "DS",
		44:    "SSHFP",
		45:    "IPSECKEY",
		46:    "RRSIG",
		47:    "NSEC",
		48:    "DNSKEY",
		49:    "DHCID",
		50:    "NSEC3",
		51:    "NSEC3PARAM",
		52:    "TLSA",
		53:    "SMIMEA",
		55:    "HIP",
		59:    "CDS",
		60:    "CDNSKEY",
		61:    "OPENPGPKEY",
		62:    "CSYNC",
		63:    "ZONEMD",
		64:    "SVCB",
		65:    "HTTPS",
		108:   "EUI48",
		109:   "EUI64",
		249:   "TKEY",
		250:   "TSIG",
		251:   "IXFR",
		252:   "AXFR",
		255:   "ANY",
		256:   "URI",
		257:   "CAA",
		32768: "TA",
		32769: "DLV",
	}
	DNSRecordType_value = map[string]int32{
		"RECORD_UNKNOWN": 0,
		"A":              1,
		"NS":             2,
		"CNAME":          5,
		"SOA":            6,
		"PTR":            12,
		"HINFO":          13,
		"MX":             15,
		"TXT":            16,
		"RP":             17,
		"AFSDB":          18,
		"SIG":            24,
		"KEY":            25,
		"AAAA":           28,
		"LOC":            29,
		"SRV":            33,
		"NAPTR":          35,
		"KX":             36,
		"CERT":           37,
		"DNAME":          39,
		"OPT":            41,
		"APL":            42,
		"DS":             43,
		"SSHFP":          44,
		"IPSECKEY":       45,
		"RRSIG":          46,
		"NSEC":           47,
		"DNSKEY":         48,
		"DHCID":          49,
		"NSEC3":          50,
		"NSEC3PARAM":     51,
		"TLSA":           52,
		"SMIMEA":         53,
		"HIP":            55,
		"CDS":            59,
		"CDNSKEY":        60,
		"OPENPGPKEY":     61,
		"CSYNC":          62,
		"ZONEMD":         63,
		"SVCB":           64,
		"HTTPS":          65,
		"EUI48":          108,
		"EUI64":          109,
		"TKEY":           249,
		"TSIG":           250,
		"IXFR":           251,
		"AXFR":           252,
		"ANY":            255,
		"URI":            256,
		"CAA":            257,
		"TA":             32768,
		"DLV":            32769,
	}
)

func (x DNSRecordType) Enum() *DNSRecordType {
	p := new(DNSRecordType)
	*p = x
	return p
}

func (x DNSRecordType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DNSRecordType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_domainpb_dns_record_proto_enumTypes[0].Descriptor()
}

func (DNSRecordType) Type() protoreflect.EnumType {
	return &file_proto_domainpb_dns_record_proto_enumTypes[0]
}

func (x DNSRecordType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DNSRecordType.Descriptor instead.
func (DNSRecordType) EnumDescriptor() ([]byte, []int) {
	return file_proto_domainpb_dns_record_proto_rawDescGZIP(), []int{0}
}

type Class int32

const (
	// Just interpret this as Internet for now. This enum only exists so that we stay in sync with the actual DNS spec / in case we need it later
	Class_CLASS_UNKNOWN Class = 0
	Class_Internet      Class = 1 // others are defined but seem mostly esoteric, can add if needed. May be useful to use this ourselves at some point though...
)

// Enum value maps for Class.
var (
	Class_name = map[int32]string{
		0: "CLASS_UNKNOWN",
		1: "Internet",
	}
	Class_value = map[string]int32{
		"CLASS_UNKNOWN": 0,
		"Internet":      1,
	}
)

func (x Class) Enum() *Class {
	p := new(Class)
	*p = x
	return p
}

func (x Class) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Class) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_domainpb_dns_record_proto_enumTypes[1].Descriptor()
}

func (Class) Type() protoreflect.EnumType {
	return &file_proto_domainpb_dns_record_proto_enumTypes[1]
}

func (x Class) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Class.Descriptor instead.
func (Class) EnumDescriptor() ([]byte, []int) {
	return file_proto_domainpb_dns_record_proto_rawDescGZIP(), []int{1}
}

type DNSRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  DNSRecordType          `protobuf:"varint,1,opt,name=type,proto3,enum=domain.DNSRecordType" json:"type,omitempty"`
	// Fully qualified domain name as per the DNS resource record spec. TODO - make sure this is the right structure
	Target     *Domain `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Class      Class   `protobuf:"varint,3,opt,name=class,proto3,enum=domain.Class" json:"class,omitempty"`
	TtlSeconds int32   `protobuf:"varint,4,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	// TODO make indivudal dns record formats typed and oneof {} wrap them
	//
	// Types that are valid to be assigned to Format:
	//
	//	*DNSRecord_Raw
	//	*DNSRecord_Text
	Format        isDNSRecord_Format `protobuf_oneof:"format"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSRecord) Reset() {
	*x = DNSRecord{}
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSRecord) ProtoMessage() {}

func (x *DNSRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSRecord.ProtoReflect.Descriptor instead.
func (*DNSRecord) Descriptor() ([]byte, []int) {
	return file_proto_domainpb_dns_record_proto_rawDescGZIP(), []int{0}
}

func (x *DNSRecord) GetType() DNSRecordType {
	if x != nil {
		return x.Type
	}
	return DNSRecordType_RECORD_UNKNOWN
}

func (x *DNSRecord) GetTarget() *Domain {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *DNSRecord) GetClass() Class {
	if x != nil {
		return x.Class
	}
	return Class_CLASS_UNKNOWN
}

func (x *DNSRecord) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *DNSRecord) GetFormat() isDNSRecord_Format {
	if x != nil {
		return x.Format
	}
	return nil
}

func (x *DNSRecord) GetRaw() []byte {
	if x != nil {
		if x, ok := x.Format.(*DNSRecord_Raw); ok {
			return x.Raw
		}
	}
	return nil
}

func (x *DNSRecord) GetText() string {
	if x != nil {
		if x, ok := x.Format.(*DNSRecord_Text); ok {
			return x.Text
		}
	}
	return ""
}

type isDNSRecord_Format interface {
	isDNSRecord_Format()
}

type DNSRecord_Raw struct {
	Raw []byte `protobuf:"bytes,5,opt,name=raw,proto3,oneof"`
}

type DNSRecord_Text struct {
	Text string `protobuf:"bytes,6,opt,name=text,proto3,oneof"`
}

func (*DNSRecord_Raw) isDNSRecord_Format() {}

func (*DNSRecord_Text) isDNSRecord_Format() {}

var File_proto_domainpb_dns_record_proto protoreflect.FileDescriptor

const file_proto_domainpb_dns_record_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/domainpb/dns_record.proto\x12\x06domain\x1a\x1bproto/domainpb/domain.proto\"\xd8\x01\n" +
	"\tDNSRecord\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.domain.DNSRecordTypeR\x04type\x12&\n" +
	"\x06target\x18\x02 \x01(\v2\x0e.domain.DomainR\x06target\x12#\n" +
	"\x05class\x18\x03 \x01(\x0e2\r.domain.ClassR\x05class\x12\x1f\n" +
	"\vttl_seconds\x18\x04 \x01(\x05R\n" +
	"ttlSeconds\x12\x12\n" +
	"\x03raw\x18\x05 \x01(\fH\x00R\x03raw\x12\x14\n" +
	"\x04text\x18\x06 \x01(\tH\x00R\x04textB\b\n" +
	"\x06format*\xb4\x04\n" +
	"\rDNSRecordType\x12\x12\n" +
	"\x0eRECORD_UNKNOWN\x10\x00\x12\x05\n" +
	"\x01A\x10\x01\x12\x06\n" +
	"\x02NS\x10\x02\x12\t\n" +
	"\x05CNAME\x10\x05\x12\a\n" +
	"\x03SOA\x10\x06\x12\a\n" +
	"\x03PTR\x10\f\x12\t\n" +
	"\x05HINFO\x10\r\x12\x06\n" +
	"\x02MX\x10\x0f\x12\a\n" +
	"\x03TXT\x10\x10\x12\x06\n" +
	"\x02RP\x10\x11\x12\t\n" +
	"\x05AFSDB\x10\x12\x12\a\n" +
	"\x03SIG\x10\x18\x12\a\n" +
	"\x03KEY\x10\x19\x12\b\n" +
	"\x04AAAA\x10\x1c\x12\a\n" +
	"\x03LOC\x10\x1d\x12\a\n" +
	"\x03SRV\x10!\x12\t\n" +
	"\x05NAPTR\x10#\x12\x06\n" +
	"\x02KX\x10$\x12\b\n" +
	"\x04CERT\x10%\x12\t\n" +
	"\x05DNAME\x10'\x12\a\n" +
	"\x03OPT\x10)\x12\a\n" +
	"\x03APL\x10*\x12\x06\n" +
	"\x02DS\x10+\x12\t\n" +
	"\x05SSHFP\x10,\x12\f\n" +
	"\bIPSECKEY\x10-\x12\t\n" +
	"\x05RRSIG\x10.\x12\b\n" +
	"\x04NSEC\x10/\x12\n" +
	"\n" +
	"\x06DNSKEY\x100\x12\t\n" +
	"\x05DHCID\x101\x12\t\n" +
	"\x05NSEC3\x102\x12\x0e\n" +
	"\n" +
	"NSEC3PARAM\x103\x12\b\n" +
	"\x04TLSA\x104\x12\n" +
	"\n" +
	"\x06SMIMEA\x105\x12\a\n" +
	"\x03HIP\x107\x12\a\n" +
	"\x03CDS\x10;\x12\v\n" +
	"\aCDNSKEY\x10<\x12\x0e\n" +
	"\n" +
	"OPENPGPKEY\x10=\x12\t\n" +
	"\x05CSYNC\x10>\x12\n" +
	"\n" +
	"\x06ZONEMD\x10?\x12\b\n" +
	"\x04SVCB\x10@\x12\t\n" +
	"\x05HTTPS\x10A\x12\t\n" +
	"\x05EUI48\x10l\x12\t\n" +
	"\x05EUI64\x10m\x12\t\n" +
	"\x04TKEY\x10\xf9\x01\x12\t\n" +
	"\x04TSIG\x10\xfa\x01\x12\t\n" +
	"\x04IXFR\x10\xfb\x01\x12\t\n" +
	"\x04AXFR\x10\xfc\x01\x12\b\n" +
	"\x03ANY\x10\xff\x01\x12\b\n" +
	"\x03URI\x10\x80\x02\x12\b\n" +
	"\x03CAA\x10\x81\x02\x12\b\n" +
	"\x02TA\x10\x80\x80\x02\x12\t\n" +
	"\x03DLV\x10\x81\x80\x02*(\n" +
	"\x05Class\x12\x11\n" +
	"\rCLASS_UNKNOWN\x10\x00\x12\f\n" +
	"\bInternet\x10\x01B=Z;github.com/accretional/proto-domain/proto/domainpb;domainpbb\x06proto3"

var (
	file_proto_domainpb_dns_record_proto_rawDescOnce sync.Once
	file_proto_domainpb_dns_record_proto_rawDescData []byte
)

func file_proto_domainpb_dns_record_proto_rawDescGZIP() []byte {
	file_proto_domainpb_dns_record_proto_rawDescOnce.Do(func() {
		file_proto_domainpb_dns_record_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_domainpb_dns_record_proto_rawDesc), len(file_proto_domainpb_dns_record_proto_rawDesc)))
	})
	return file_proto_domainpb_dns_record_proto_rawDescData
}

var file_proto_domainpb_dns_record_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_domainpb_dns_record_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_domainpb_dns_record_proto_goTypes = []any{
	(DNSRecordType)(0), // 0: domain.DNSRecordType
	(Class)(0),         // 1: domain.Class
	(*DNSRecord)(nil),  // 2: domain.DNSRecord
	(*Domain)(nil),     // 3: domain.Domain
}
var file_proto_domainpb_dns_record_proto_depIdxs = []int32{
	0, // 0: domain.DNSRecord.type:type_name -> domain.DNSRecordType
	3, // 1: domain.DNSRecord.target:type_name -> domain.Domain
	1, // 2: domain.DNSRecord.class:type_name -> domain.Class
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_domainpb_dns_record_proto_init() }
func file_proto_domainpb_dns_record_proto_init() {
	if File_proto_domainpb_dns_record_proto != nil {
		return
	}
	file_proto_domainpb_domain_proto_init()
	file_proto_domainpb_dns_record_proto_msgTypes[0].OneofWrappers = []any{
		(*DNSRecord_Raw)(nil),
		(*DNSRecord_Text)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_domainpb_dns_record_proto_rawDesc), len(file_proto_domainpb_dns_record_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_domainpb_dns_record_proto_goTypes,
		DependencyIndexes: file_proto_domainpb_dns_record_proto_depIdxs,
		EnumInfos:         file_proto_domainpb_dns_record_proto_enumTypes,
		MessageInfos:      file_proto_domainpb_dns_record_proto_msgTypes,
	}.Build()
	File_proto_domainpb_dns_record_proto = out.File
	file_proto_domainpb_dns_record_proto_goTypes = nil
	file_proto_domainpb_dns_record_proto_depIdxs = nil
}
