// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/domainpb/dns_record.proto

package domainpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DNSRecordType int32

const (
	DNSRecordType_RECORD_UNKNOWN DNSRecordType = 0
	// Type id 1, RFC 1035. Address record. Returns a 32-bit IPv4 address; most
	// commonly used to map hostnames to an IP address, but also used for DNSBLs,
	// storing subnet masks, etc.
	DNSRecordType_A DNSRecordType = 1
	// Type id 2, RFC 1035. Name server record. Delegates a DNS zone to use the
	// given authoritative name servers.
	DNSRecordType_NS DNSRecordType = 2
	// Type id 5, RFC 1035. Canonical name record. Alias of one name to another;
	// the DNS lookup will continue by retrying the lookup with the new name.
	DNSRecordType_CNAME DNSRecordType = 5
	// Type id 6, RFC 1035 / RFC 2308. Start of authority record. Specifies
	// authoritative information about a DNS zone, including the primary name
	// server, the email of the domain administrator, the domain serial number,
	// and several timers relating to refreshing the zone.
	DNSRecordType_SOA DNSRecordType = 6
	// Type id 12, RFC 1035. PTR resource record. Pointer to a canonical name.
	// Unlike a CNAME, DNS processing stops and just the name is returned. Most
	// commonly used for reverse DNS lookups, but also for things like DNS-SD.
	DNSRecordType_PTR DNSRecordType = 12
	// Type id 13, RFC 8482 / RFC 1035. Host information / placeholder record.
	// Originally intended to inform about a host's OS and hardware; repurposed
	// by RFC 8482 to be used while responding to ANY queries.
	DNSRecordType_HINFO DNSRecordType = 13
	// Type id 15, RFC 1035 / RFC 7505. Mail exchange record. List of mail
	// exchange servers that accept email for a domain.
	DNSRecordType_MX DNSRecordType = 15
	// Type id 16, RFC 1035. Text record. Originally for arbitrary human-readable
	// text; now more often carries machine-readable data such as SPF, DKIM,
	// DMARC, DNS-SD, opportunistic encryption, etc.
	DNSRecordType_TXT DNSRecordType = 16
	// Type id 17, RFC 1183. Responsible Person. Information about the
	// responsible person(s) for the domain. Usually an email address with the
	// @ replaced by a dot.
	DNSRecordType_RP DNSRecordType = 17
	// Type id 18, RFC 1183. AFS database record. Location of database servers
	// of an AFS cell. Used by AFS clients to contact AFS cells outside their
	// local domain. A subtype is used by the obsolete DCE/DFS file system.
	DNSRecordType_AFSDB DNSRecordType = 18
	// Type id 24, RFC 2535. Signature record. Used in SIG(0) (RFC 2931) and
	// TKEY (RFC 2930). RFC 3755 designated RRSIG as the replacement for SIG
	// for use within DNSSEC.
	DNSRecordType_SIG DNSRecordType = 24
	// Type id 25, RFC 2535 / RFC 2930. Key record. Used only for SIG(0) and
	// TKEY. RFC 3445 limited their use to DNSSEC; RFC 3755 designates DNSKEY
	// as the replacement within DNSSEC, and RFC 4025 designates IPSECKEY as
	// the replacement for use with IPsec.
	DNSRecordType_KEY DNSRecordType = 25
	// Type id 28, RFC 3596. IPv6 address record. Returns a 128-bit IPv6 address,
	// most commonly used to map hostnames to an IP address of the host.
	DNSRecordType_AAAA DNSRecordType = 28
	// Type id 29, RFC 1876. Location record. Specifies a geographical location
	// associated with a domain name.
	DNSRecordType_LOC DNSRecordType = 29
	// Type id 33, RFC 2782. Service locator. Generalized service location
	// record, used for newer protocols instead of creating protocol-specific
	// records such as MX.
	DNSRecordType_SRV DNSRecordType = 33
	// Type id 35, RFC 3403. Naming Authority Pointer. Allows regular-expression-
	// based rewriting of domain names which can then be used as URIs, further
	// domain names to lookups, etc.
	DNSRecordType_NAPTR DNSRecordType = 35
	// Type id 36, RFC 2230. Key Exchanger record. Used with some cryptographic
	// systems (not DNSSEC) to identify a key management agent for the
	// associated domain name. Informational status, limited deployment.
	DNSRecordType_KX DNSRecordType = 36
	// Type id 37, RFC 4398. Certificate record. Stores digital certificates in
	// various forms (PKIX, SPKI, PGP, etc.).
	DNSRecordType_CERT DNSRecordType = 37
	// Type id 39, RFC 6672. Delegation name record. Alias for a name and all
	// its subnames, unlike CNAME, which is an alias for only the exact name.
	// Like CNAME, the DNS lookup will continue by retrying with the new name.
	DNSRecordType_DNAME DNSRecordType = 39
	// Type id 41, RFC 6891. OPT pseudo-record needed to support EDNS.
	DNSRecordType_OPT DNSRecordType = 41
	// Type id 42, RFC 3123. Address Prefix List. Specifies lists of address
	// ranges, e.g. in CIDR format, for various address families. Experimental.
	DNSRecordType_APL DNSRecordType = 42
	// Type id 43, RFC 4034. Delegation signer. The record used to identify the
	// DNSSEC signing key of a delegated zone.
	DNSRecordType_DS DNSRecordType = 43
	// Type id 44, RFC 4255. SSH public key fingerprint. Resource record for
	// publishing SSH public host key fingerprints in DNS, to aid in verifying
	// host authenticity. RFC 6594 defines ECC SSH keys and SHA-256 hashes.
	DNSRecordType_SSHFP DNSRecordType = 44
	// Type id 45, RFC 4025. IPsec Key. Key record that can be used with IPsec.
	DNSRecordType_IPSECKEY DNSRecordType = 45
	// Type id 46, RFC 4034. DNSSEC signature for a record set. Uses the same
	// format as the SIG record.
	DNSRecordType_RRSIG DNSRecordType = 46
	// Type id 47, RFC 4034. Next Secure record. Part of DNSSEC—used to prove
	// a name does not exist. Uses the same format as the (obsolete) NXT record.
	DNSRecordType_NSEC DNSRecordType = 47
	// Type id 48, RFC 4034. DNS Key record used in DNSSEC. Uses the same
	// format as the KEY record.
	DNSRecordType_DNSKEY DNSRecordType = 48
	// Type id 49, RFC 4701. DHCP identifier. Used in conjunction with the FQDN
	// option to DHCP.
	DNSRecordType_DHCID DNSRecordType = 49
	// Type id 50, RFC 5155. Next Secure record version 3. An extension to
	// DNSSEC that allows proof of nonexistence for a name without permitting
	// zone walking.
	DNSRecordType_NSEC3 DNSRecordType = 50
	// Type id 51, RFC 5155. NSEC3 parameters. Parameter record for use with
	// NSEC3.
	DNSRecordType_NSEC3PARAM DNSRecordType = 51
	// Type id 52, RFC 6698. TLSA certificate association. A record for DANE,
	// used to associate a TLS server certificate or public key with the domain
	// name where the record is found.
	DNSRecordType_TLSA DNSRecordType = 52
	// Type id 53, RFC 8162. S/MIME certificate association. Associates an
	// S/MIME certificate with a domain name for sender authentication.
	DNSRecordType_SMIMEA DNSRecordType = 53
	// Type id 55, RFC 8005. Host Identity Protocol. Method of separating the
	// end-point identifier and locator roles of IP addresses.
	DNSRecordType_HIP DNSRecordType = 55
	// Type id 59, RFC 7344. Child DS. Child copy of DS record, for transfer
	// to parent.
	DNSRecordType_CDS DNSRecordType = 59
	// Type id 60, RFC 7344. Child copy of DNSKEY record, for transfer to
	// parent.
	DNSRecordType_CDNSKEY DNSRecordType = 60
	// Type id 61, RFC 7929. OpenPGP public key record. A DANE method for
	// publishing and locating OpenPGP public keys in DNS for a specific email
	// address.
	DNSRecordType_OPENPGPKEY DNSRecordType = 61
	// Type id 62, RFC 7477. Child-to-Parent Synchronization. Specifies a
	// synchronization mechanism between a child and a parent DNS zone, e.g.
	// declaring the same NS records in both zones.
	DNSRecordType_CSYNC DNSRecordType = 62
	// Type id 63, RFC 8976. Message Digests for DNS Zones. Provides a
	// cryptographic message digest over DNS zone data at rest.
	DNSRecordType_ZONEMD DNSRecordType = 63
	// Type id 64, RFC 9460. Service Binding. Provides metadata and other
	// information that can help clients connect to the host. The more general
	// SVCB record can convey supported protocols, alternative endpoints, and
	// some types of aliasing not supported by CNAME.
	DNSRecordType_SVCB DNSRecordType = 64
	// Type id 65, RFC 9460. HTTPS Binding. Specialised SVCB record providing
	// connection information for HTTPS, allowing more secure connections (e.g.
	// Encrypted Client Hello) and lower first-connection latency.
	DNSRecordType_HTTPS DNSRecordType = 65
	// Type id 108, RFC 7043. MAC address (EUI-48). A 48-bit IEEE Extended
	// Unique Identifier.
	DNSRecordType_EUI48 DNSRecordType = 108
	// Type id 109, RFC 7043. MAC address (EUI-64). A 64-bit IEEE Extended
	// Unique Identifier.
	DNSRecordType_EUI64 DNSRecordType = 109
	// Type id 249, RFC 2930. Transaction Key record. A method of providing
	// keying material to be used with TSIG that is encrypted under the public
	// key in an accompanying KEY RR.
	DNSRecordType_TKEY DNSRecordType = 249
	// Type id 250, RFC 2845. Transaction Signature. Can be used to authenticate
	// dynamic updates as coming from an approved client, or to authenticate
	// responses as coming from an approved recursive name server.
	DNSRecordType_TSIG DNSRecordType = 250
	// Type id 251, RFC 1996. Incremental Zone Transfer. Requests a zone
	// transfer of the given zone but only differences from a previous serial
	// number. May fall back to AXFR if deltas are unavailable.
	DNSRecordType_IXFR DNSRecordType = 251
	// Type id 252, RFC 1035. Authoritative Zone Transfer. Transfer entire zone
	// file from the primary name server to secondary name servers.
	DNSRecordType_AXFR DNSRecordType = 252
	// Type id 255, RFC 1035. All cached records (commonly referred to as ANY
	// or *). Returns all records of all types known to the name server. Since
	// RFC 8482, many providers (e.g. Cloudflare) return only minimal responses
	// to ANY queries instead of enumerating records.
	DNSRecordType_ANY DNSRecordType = 255
	// Type id 256, RFC 7553. Uniform Resource Identifier. Can be used for
	// publishing mappings from hostnames to URIs.
	DNSRecordType_URI DNSRecordType = 256
	// Type id 257, RFC 8659. Certification Authority Authorization. Constrains
	// acceptable CAs for a host/domain.
	DNSRecordType_CAA DNSRecordType = 257
	// Type id 32768, no RFC. DNSSEC Trust Authorities. Part of a deployment
	// proposal for DNSSEC without a signed DNS root. Uses the same format as
	// the DS record.
	DNSRecordType_TA DNSRecordType = 32768
	// Type id 32769, RFC 4431. DNSSEC Lookaside Validation record. For
	// publishing DNSSEC trust anchors outside of the DNS delegation chain.
	// Uses the same format as the DS record; RFC 5074 describes its use.
	DNSRecordType_DLV DNSRecordType = 32769
)

// Enum value maps for DNSRecordType.
var (
	DNSRecordType_name = map[int32]string{
		0:     "RECORD_UNKNOWN",
		1:     "A",
		2:     "NS",
		5:     "CNAME",
		6:     "SOA",
		12:    "PTR",
		13:    "HINFO",
		15:    "MX",
		16:    "TXT",
		17:    "RP",
		18:    "AFSDB",
		24:    "SIG",
		25:    "KEY",
		28:    "AAAA",
		29:    "LOC",
		33:    "SRV",
		35:    "NAPTR",
		36:    "KX",
		37:    "CERT",
		39:    "DNAME",
		41:    "OPT",
		42:    "APL",
		43:    "DS",
		44:    "SSHFP",
		45:    "IPSECKEY",
		46:    "RRSIG",
		47:    "NSEC",
		48:    "DNSKEY",
		49:    "DHCID",
		50:    "NSEC3",
		51:    "NSEC3PARAM",
		52:    "TLSA",
		53:    "SMIMEA",
		55:    "HIP",
		59:    "CDS",
		60:    "CDNSKEY",
		61:    "OPENPGPKEY",
		62:    "CSYNC",
		63:    "ZONEMD",
		64:    "SVCB",
		65:    "HTTPS",
		108:   "EUI48",
		109:   "EUI64",
		249:   "TKEY",
		250:   "TSIG",
		251:   "IXFR",
		252:   "AXFR",
		255:   "ANY",
		256:   "URI",
		257:   "CAA",
		32768: "TA",
		32769: "DLV",
	}
	DNSRecordType_value = map[string]int32{
		"RECORD_UNKNOWN": 0,
		"A":              1,
		"NS":             2,
		"CNAME":          5,
		"SOA":            6,
		"PTR":            12,
		"HINFO":          13,
		"MX":             15,
		"TXT":            16,
		"RP":             17,
		"AFSDB":          18,
		"SIG":            24,
		"KEY":            25,
		"AAAA":           28,
		"LOC":            29,
		"SRV":            33,
		"NAPTR":          35,
		"KX":             36,
		"CERT":           37,
		"DNAME":          39,
		"OPT":            41,
		"APL":            42,
		"DS":             43,
		"SSHFP":          44,
		"IPSECKEY":       45,
		"RRSIG":          46,
		"NSEC":           47,
		"DNSKEY":         48,
		"DHCID":          49,
		"NSEC3":          50,
		"NSEC3PARAM":     51,
		"TLSA":           52,
		"SMIMEA":         53,
		"HIP":            55,
		"CDS":            59,
		"CDNSKEY":        60,
		"OPENPGPKEY":     61,
		"CSYNC":          62,
		"ZONEMD":         63,
		"SVCB":           64,
		"HTTPS":          65,
		"EUI48":          108,
		"EUI64":          109,
		"TKEY":           249,
		"TSIG":           250,
		"IXFR":           251,
		"AXFR":           252,
		"ANY":            255,
		"URI":            256,
		"CAA":            257,
		"TA":             32768,
		"DLV":            32769,
	}
)

func (x DNSRecordType) Enum() *DNSRecordType {
	p := new(DNSRecordType)
	*p = x
	return p
}

func (x DNSRecordType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DNSRecordType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_domainpb_dns_record_proto_enumTypes[0].Descriptor()
}

func (DNSRecordType) Type() protoreflect.EnumType {
	return &file_proto_domainpb_dns_record_proto_enumTypes[0]
}

func (x DNSRecordType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DNSRecordType.Descriptor instead.
func (DNSRecordType) EnumDescriptor() ([]byte, []int) {
	return file_proto_domainpb_dns_record_proto_rawDescGZIP(), []int{0}
}

type Class int32

const (
	// Just interpret this as Internet for now. This enum only exists so that we stay in sync with the actual DNS spec / in case we need it later
	Class_CLASS_UNKNOWN Class = 0
	Class_Internet      Class = 1 // others are defined but seem mostly esoteric, can add if needed. May be useful to use this ourselves at some point though...
)

// Enum value maps for Class.
var (
	Class_name = map[int32]string{
		0: "CLASS_UNKNOWN",
		1: "Internet",
	}
	Class_value = map[string]int32{
		"CLASS_UNKNOWN": 0,
		"Internet":      1,
	}
)

func (x Class) Enum() *Class {
	p := new(Class)
	*p = x
	return p
}

func (x Class) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Class) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_domainpb_dns_record_proto_enumTypes[1].Descriptor()
}

func (Class) Type() protoreflect.EnumType {
	return &file_proto_domainpb_dns_record_proto_enumTypes[1]
}

func (x Class) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Class.Descriptor instead.
func (Class) EnumDescriptor() ([]byte, []int) {
	return file_proto_domainpb_dns_record_proto_rawDescGZIP(), []int{1}
}

type DNSRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type is the DNS RR type code. Redundant with the body oneof case
	// (the case selects the type), but kept as a top-level field so that
	// walker code that doesn't switch on the body can still log/filter.
	Type DNSRecordType `protobuf:"varint,1,opt,name=type,proto3,enum=domain.DNSRecordType" json:"type,omitempty"`
	// target is the owner name the record belongs to (the FQDN we
	// queried), not the RDATA inside the body.
	Target     *Domain `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Class      Class   `protobuf:"varint,3,opt,name=class,proto3,enum=domain.Class" json:"class,omitempty"`
	TtlSeconds int32   `protobuf:"varint,4,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	// body carries the typed RDATA for the record. Exactly one case is
	// set per record. The case must match `type`; mismatches are caller
	// bugs. Records for types not modelled here (DNSSEC types, ANY
	// pseudo-responses, etc.) are not emitted at all — there is no raw
	// fallback in this API.
	//
	// Types that are valid to be assigned to Body:
	//
	//	*DNSRecord_A
	//	*DNSRecord_Aaaa
	//	*DNSRecord_Cname
	//	*DNSRecord_Dname
	//	*DNSRecord_Ns
	//	*DNSRecord_Mx
	//	*DNSRecord_Txt
	//	*DNSRecord_Soa
	//	*DNSRecord_Loc
	//	*DNSRecord_Hinfo
	//	*DNSRecord_Rp
	//	*DNSRecord_Afsdb
	//	*DNSRecord_Naptr
	//	*DNSRecord_Kx
	//	*DNSRecord_Sshfp
	//	*DNSRecord_Svcb
	//	*DNSRecord_Https
	//	*DNSRecord_Caa
	//	*DNSRecord_Uri
	Body          isDNSRecord_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSRecord) Reset() {
	*x = DNSRecord{}
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSRecord) ProtoMessage() {}

func (x *DNSRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSRecord.ProtoReflect.Descriptor instead.
func (*DNSRecord) Descriptor() ([]byte, []int) {
	return file_proto_domainpb_dns_record_proto_rawDescGZIP(), []int{0}
}

func (x *DNSRecord) GetType() DNSRecordType {
	if x != nil {
		return x.Type
	}
	return DNSRecordType_RECORD_UNKNOWN
}

func (x *DNSRecord) GetTarget() *Domain {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *DNSRecord) GetClass() Class {
	if x != nil {
		return x.Class
	}
	return Class_CLASS_UNKNOWN
}

func (x *DNSRecord) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *DNSRecord) GetBody() isDNSRecord_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *DNSRecord) GetA() *ARecord {
	if x != nil {
		if x, ok := x.Body.(*DNSRecord_A); ok {
			return x.A
		}
	}
	return nil
}

func (x *DNSRecord) GetAaaa() *AAAARecord {
	if x != nil {
		if x, ok := x.Body.(*DNSRecord_Aaaa); ok {
			return x.Aaaa
		}
	}
	return nil
}

func (x *DNSRecord) GetCname() *CNAMERecord {
	if x != nil {
		if x, ok := x.Body.(*DNSRecord_Cname); ok {
			return x.Cname
		}
	}
	return nil
}

func (x *DNSRecord) GetDname() *DNAMERecord {
	if x != nil {
		if x, ok := x.Body.(*DNSRecord_Dname); ok {
			return x.Dname
		}
	}
	return nil
}

func (x *DNSRecord) GetNs() *NSRecord {
	if x != nil {
		if x, ok := x.Body.(*DNSRecord_Ns); ok {
			return x.Ns
		}
	}
	return nil
}

func (x *DNSRecord) GetMx() *MXRecord {
	if x != nil {
		if x, ok := x.Body.(*DNSRecord_Mx); ok {
			return x.Mx
		}
	}
	return nil
}

func (x *DNSRecord) GetTxt() *TXTRecord {
	if x != nil {
		if x, ok := x.Body.(*DNSRecord_Txt); ok {
			return x.Txt
		}
	}
	return nil
}

func (x *DNSRecord) GetSoa() *SOARecord {
	if x != nil {
		if x, ok := x.Body.(*DNSRecord_Soa); ok {
			return x.Soa
		}
	}
	return nil
}

func (x *DNSRecord) GetLoc() *LOCRecord {
	if x != nil {
		if x, ok := x.Body.(*DNSRecord_Loc); ok {
			return x.Loc
		}
	}
	return nil
}

func (x *DNSRecord) GetHinfo() *HINFORecord {
	if x != nil {
		if x, ok := x.Body.(*DNSRecord_Hinfo); ok {
			return x.Hinfo
		}
	}
	return nil
}

func (x *DNSRecord) GetRp() *RPRecord {
	if x != nil {
		if x, ok := x.Body.(*DNSRecord_Rp); ok {
			return x.Rp
		}
	}
	return nil
}

func (x *DNSRecord) GetAfsdb() *AFSDBRecord {
	if x != nil {
		if x, ok := x.Body.(*DNSRecord_Afsdb); ok {
			return x.Afsdb
		}
	}
	return nil
}

func (x *DNSRecord) GetNaptr() *NAPTRRecord {
	if x != nil {
		if x, ok := x.Body.(*DNSRecord_Naptr); ok {
			return x.Naptr
		}
	}
	return nil
}

func (x *DNSRecord) GetKx() *KXRecord {
	if x != nil {
		if x, ok := x.Body.(*DNSRecord_Kx); ok {
			return x.Kx
		}
	}
	return nil
}

func (x *DNSRecord) GetSshfp() *SSHFPRecord {
	if x != nil {
		if x, ok := x.Body.(*DNSRecord_Sshfp); ok {
			return x.Sshfp
		}
	}
	return nil
}

func (x *DNSRecord) GetSvcb() *SVCBRecord {
	if x != nil {
		if x, ok := x.Body.(*DNSRecord_Svcb); ok {
			return x.Svcb
		}
	}
	return nil
}

func (x *DNSRecord) GetHttps() *HTTPSRecord {
	if x != nil {
		if x, ok := x.Body.(*DNSRecord_Https); ok {
			return x.Https
		}
	}
	return nil
}

func (x *DNSRecord) GetCaa() *CAARecord {
	if x != nil {
		if x, ok := x.Body.(*DNSRecord_Caa); ok {
			return x.Caa
		}
	}
	return nil
}

func (x *DNSRecord) GetUri() *URIRecord {
	if x != nil {
		if x, ok := x.Body.(*DNSRecord_Uri); ok {
			return x.Uri
		}
	}
	return nil
}

type isDNSRecord_Body interface {
	isDNSRecord_Body()
}

type DNSRecord_A struct {
	A *ARecord `protobuf:"bytes,5,opt,name=a,proto3,oneof"`
}

type DNSRecord_Aaaa struct {
	Aaaa *AAAARecord `protobuf:"bytes,6,opt,name=aaaa,proto3,oneof"`
}

type DNSRecord_Cname struct {
	Cname *CNAMERecord `protobuf:"bytes,7,opt,name=cname,proto3,oneof"`
}

type DNSRecord_Dname struct {
	Dname *DNAMERecord `protobuf:"bytes,8,opt,name=dname,proto3,oneof"`
}

type DNSRecord_Ns struct {
	Ns *NSRecord `protobuf:"bytes,9,opt,name=ns,proto3,oneof"`
}

type DNSRecord_Mx struct {
	Mx *MXRecord `protobuf:"bytes,10,opt,name=mx,proto3,oneof"`
}

type DNSRecord_Txt struct {
	Txt *TXTRecord `protobuf:"bytes,11,opt,name=txt,proto3,oneof"`
}

type DNSRecord_Soa struct {
	Soa *SOARecord `protobuf:"bytes,12,opt,name=soa,proto3,oneof"`
}

type DNSRecord_Loc struct {
	Loc *LOCRecord `protobuf:"bytes,13,opt,name=loc,proto3,oneof"`
}

type DNSRecord_Hinfo struct {
	Hinfo *HINFORecord `protobuf:"bytes,14,opt,name=hinfo,proto3,oneof"`
}

type DNSRecord_Rp struct {
	Rp *RPRecord `protobuf:"bytes,15,opt,name=rp,proto3,oneof"`
}

type DNSRecord_Afsdb struct {
	Afsdb *AFSDBRecord `protobuf:"bytes,16,opt,name=afsdb,proto3,oneof"`
}

type DNSRecord_Naptr struct {
	Naptr *NAPTRRecord `protobuf:"bytes,17,opt,name=naptr,proto3,oneof"`
}

type DNSRecord_Kx struct {
	Kx *KXRecord `protobuf:"bytes,18,opt,name=kx,proto3,oneof"`
}

type DNSRecord_Sshfp struct {
	Sshfp *SSHFPRecord `protobuf:"bytes,19,opt,name=sshfp,proto3,oneof"`
}

type DNSRecord_Svcb struct {
	Svcb *SVCBRecord `protobuf:"bytes,20,opt,name=svcb,proto3,oneof"`
}

type DNSRecord_Https struct {
	Https *HTTPSRecord `protobuf:"bytes,21,opt,name=https,proto3,oneof"`
}

type DNSRecord_Caa struct {
	Caa *CAARecord `protobuf:"bytes,22,opt,name=caa,proto3,oneof"`
}

type DNSRecord_Uri struct {
	Uri *URIRecord `protobuf:"bytes,23,opt,name=uri,proto3,oneof"`
}

func (*DNSRecord_A) isDNSRecord_Body() {}

func (*DNSRecord_Aaaa) isDNSRecord_Body() {}

func (*DNSRecord_Cname) isDNSRecord_Body() {}

func (*DNSRecord_Dname) isDNSRecord_Body() {}

func (*DNSRecord_Ns) isDNSRecord_Body() {}

func (*DNSRecord_Mx) isDNSRecord_Body() {}

func (*DNSRecord_Txt) isDNSRecord_Body() {}

func (*DNSRecord_Soa) isDNSRecord_Body() {}

func (*DNSRecord_Loc) isDNSRecord_Body() {}

func (*DNSRecord_Hinfo) isDNSRecord_Body() {}

func (*DNSRecord_Rp) isDNSRecord_Body() {}

func (*DNSRecord_Afsdb) isDNSRecord_Body() {}

func (*DNSRecord_Naptr) isDNSRecord_Body() {}

func (*DNSRecord_Kx) isDNSRecord_Body() {}

func (*DNSRecord_Sshfp) isDNSRecord_Body() {}

func (*DNSRecord_Svcb) isDNSRecord_Body() {}

func (*DNSRecord_Https) isDNSRecord_Body() {}

func (*DNSRecord_Caa) isDNSRecord_Body() {}

func (*DNSRecord_Uri) isDNSRecord_Body() {}

// A is an IPv4 address record (RFC 1035). ipv4 is the wire 4-byte
// address; callers can render with net.IP.
type ARecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ipv4          []byte                 `protobuf:"bytes,1,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ARecord) Reset() {
	*x = ARecord{}
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ARecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ARecord) ProtoMessage() {}

func (x *ARecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ARecord.ProtoReflect.Descriptor instead.
func (*ARecord) Descriptor() ([]byte, []int) {
	return file_proto_domainpb_dns_record_proto_rawDescGZIP(), []int{1}
}

func (x *ARecord) GetIpv4() []byte {
	if x != nil {
		return x.Ipv4
	}
	return nil
}

// AAAA is an IPv6 address record (RFC 3596). ipv6 is the wire 16-byte
// address.
type AAAARecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ipv6          []byte                 `protobuf:"bytes,1,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AAAARecord) Reset() {
	*x = AAAARecord{}
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AAAARecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AAAARecord) ProtoMessage() {}

func (x *AAAARecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AAAARecord.ProtoReflect.Descriptor instead.
func (*AAAARecord) Descriptor() ([]byte, []int) {
	return file_proto_domainpb_dns_record_proto_rawDescGZIP(), []int{2}
}

func (x *AAAARecord) GetIpv6() []byte {
	if x != nil {
		return x.Ipv6
	}
	return nil
}

// CNAME is a canonical-name alias (RFC 1035). target is presentation
// form with trailing dot.
type CNAMERecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CNAMERecord) Reset() {
	*x = CNAMERecord{}
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CNAMERecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CNAMERecord) ProtoMessage() {}

func (x *CNAMERecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CNAMERecord.ProtoReflect.Descriptor instead.
func (*CNAMERecord) Descriptor() ([]byte, []int) {
	return file_proto_domainpb_dns_record_proto_rawDescGZIP(), []int{3}
}

func (x *CNAMERecord) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

// DNAME is a delegation-name record (RFC 6672). target is presentation
// form with trailing dot.
type DNAMERecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNAMERecord) Reset() {
	*x = DNAMERecord{}
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNAMERecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNAMERecord) ProtoMessage() {}

func (x *DNAMERecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNAMERecord.ProtoReflect.Descriptor instead.
func (*DNAMERecord) Descriptor() ([]byte, []int) {
	return file_proto_domainpb_dns_record_proto_rawDescGZIP(), []int{4}
}

func (x *DNAMERecord) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

// NS is an authoritative name-server record (RFC 1035). host is the
// nameserver in presentation form with trailing dot.
type NSRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NSRecord) Reset() {
	*x = NSRecord{}
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NSRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NSRecord) ProtoMessage() {}

func (x *NSRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NSRecord.ProtoReflect.Descriptor instead.
func (*NSRecord) Descriptor() ([]byte, []int) {
	return file_proto_domainpb_dns_record_proto_rawDescGZIP(), []int{5}
}

func (x *NSRecord) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

// MX is a mail-exchange record (RFC 1035). pref is preference (lower
// is preferred per RFC 5321); host is presentation form with dot.
type MXRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pref          uint32                 `protobuf:"varint,1,opt,name=pref,proto3" json:"pref,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MXRecord) Reset() {
	*x = MXRecord{}
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MXRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MXRecord) ProtoMessage() {}

func (x *MXRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MXRecord.ProtoReflect.Descriptor instead.
func (*MXRecord) Descriptor() ([]byte, []int) {
	return file_proto_domainpb_dns_record_proto_rawDescGZIP(), []int{6}
}

func (x *MXRecord) GetPref() uint32 {
	if x != nil {
		return x.Pref
	}
	return 0
}

func (x *MXRecord) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

// TXT is a text record (RFC 1035 §3.3.14). strings is the wire-form
// slice of character-string fragments; most callers concat with no
// separator (which is what net.Resolver does).
type TXTRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Strings       []string               `protobuf:"bytes,1,rep,name=strings,proto3" json:"strings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TXTRecord) Reset() {
	*x = TXTRecord{}
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TXTRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TXTRecord) ProtoMessage() {}

func (x *TXTRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TXTRecord.ProtoReflect.Descriptor instead.
func (*TXTRecord) Descriptor() ([]byte, []int) {
	return file_proto_domainpb_dns_record_proto_rawDescGZIP(), []int{7}
}

func (x *TXTRecord) GetStrings() []string {
	if x != nil {
		return x.Strings
	}
	return nil
}

// SOA is a start-of-authority record (RFC 1035).
type SOARecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ns            string                 `protobuf:"bytes,1,opt,name=ns,proto3" json:"ns,omitempty"`
	Mbox          string                 `protobuf:"bytes,2,opt,name=mbox,proto3" json:"mbox,omitempty"`
	Serial        uint32                 `protobuf:"varint,3,opt,name=serial,proto3" json:"serial,omitempty"`
	Refresh       uint32                 `protobuf:"varint,4,opt,name=refresh,proto3" json:"refresh,omitempty"`
	Retry         uint32                 `protobuf:"varint,5,opt,name=retry,proto3" json:"retry,omitempty"`
	Expire        uint32                 `protobuf:"varint,6,opt,name=expire,proto3" json:"expire,omitempty"`
	MinTtl        uint32                 `protobuf:"varint,7,opt,name=min_ttl,json=minTtl,proto3" json:"min_ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SOARecord) Reset() {
	*x = SOARecord{}
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SOARecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SOARecord) ProtoMessage() {}

func (x *SOARecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SOARecord.ProtoReflect.Descriptor instead.
func (*SOARecord) Descriptor() ([]byte, []int) {
	return file_proto_domainpb_dns_record_proto_rawDescGZIP(), []int{8}
}

func (x *SOARecord) GetNs() string {
	if x != nil {
		return x.Ns
	}
	return ""
}

func (x *SOARecord) GetMbox() string {
	if x != nil {
		return x.Mbox
	}
	return ""
}

func (x *SOARecord) GetSerial() uint32 {
	if x != nil {
		return x.Serial
	}
	return 0
}

func (x *SOARecord) GetRefresh() uint32 {
	if x != nil {
		return x.Refresh
	}
	return 0
}

func (x *SOARecord) GetRetry() uint32 {
	if x != nil {
		return x.Retry
	}
	return 0
}

func (x *SOARecord) GetExpire() uint32 {
	if x != nil {
		return x.Expire
	}
	return 0
}

func (x *SOARecord) GetMinTtl() uint32 {
	if x != nil {
		return x.MinTtl
	}
	return 0
}

// LOC is a location record (RFC 1876). latitude/longitude are
// milli-arcseconds biased by 2^31 (equator/prime meridian = 2^31).
// altitude is centimeters biased by 10_000_000 (0 = -100_000 m).
// size, horiz_pre, vert_pre are precision bytes: high nibble is the
// base-10 mantissa (1–9), low nibble the exponent in centimeters.
type LOCRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	HorizPre      uint32                 `protobuf:"varint,3,opt,name=horiz_pre,json=horizPre,proto3" json:"horiz_pre,omitempty"`
	VertPre       uint32                 `protobuf:"varint,4,opt,name=vert_pre,json=vertPre,proto3" json:"vert_pre,omitempty"`
	Latitude      uint32                 `protobuf:"varint,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     uint32                 `protobuf:"varint,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Altitude      uint32                 `protobuf:"varint,7,opt,name=altitude,proto3" json:"altitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LOCRecord) Reset() {
	*x = LOCRecord{}
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LOCRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LOCRecord) ProtoMessage() {}

func (x *LOCRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LOCRecord.ProtoReflect.Descriptor instead.
func (*LOCRecord) Descriptor() ([]byte, []int) {
	return file_proto_domainpb_dns_record_proto_rawDescGZIP(), []int{9}
}

func (x *LOCRecord) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *LOCRecord) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *LOCRecord) GetHorizPre() uint32 {
	if x != nil {
		return x.HorizPre
	}
	return 0
}

func (x *LOCRecord) GetVertPre() uint32 {
	if x != nil {
		return x.VertPre
	}
	return 0
}

func (x *LOCRecord) GetLatitude() uint32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *LOCRecord) GetLongitude() uint32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *LOCRecord) GetAltitude() uint32 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

// HINFO is a host-information record (RFC 1035 §3.3.2). Two
// character-string fragments — cpu and os.
type HINFORecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           string                 `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HINFORecord) Reset() {
	*x = HINFORecord{}
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HINFORecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HINFORecord) ProtoMessage() {}

func (x *HINFORecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HINFORecord.ProtoReflect.Descriptor instead.
func (*HINFORecord) Descriptor() ([]byte, []int) {
	return file_proto_domainpb_dns_record_proto_rawDescGZIP(), []int{10}
}

func (x *HINFORecord) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *HINFORecord) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

// RP is a responsible-person record (RFC 1183). Both fields are
// presentation-form domain names.
type RPRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mbox          string                 `protobuf:"bytes,1,opt,name=mbox,proto3" json:"mbox,omitempty"`
	Txt           string                 `protobuf:"bytes,2,opt,name=txt,proto3" json:"txt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPRecord) Reset() {
	*x = RPRecord{}
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPRecord) ProtoMessage() {}

func (x *RPRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPRecord.ProtoReflect.Descriptor instead.
func (*RPRecord) Descriptor() ([]byte, []int) {
	return file_proto_domainpb_dns_record_proto_rawDescGZIP(), []int{11}
}

func (x *RPRecord) GetMbox() string {
	if x != nil {
		return x.Mbox
	}
	return ""
}

func (x *RPRecord) GetTxt() string {
	if x != nil {
		return x.Txt
	}
	return ""
}

// AFSDB is an AFS database record (RFC 1183). subtype 1 = AFS cell
// database server; subtype 2 = DCE/NCA root cell directory node.
type AFSDBRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subtype       uint32                 `protobuf:"varint,1,opt,name=subtype,proto3" json:"subtype,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AFSDBRecord) Reset() {
	*x = AFSDBRecord{}
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AFSDBRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AFSDBRecord) ProtoMessage() {}

func (x *AFSDBRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AFSDBRecord.ProtoReflect.Descriptor instead.
func (*AFSDBRecord) Descriptor() ([]byte, []int) {
	return file_proto_domainpb_dns_record_proto_rawDescGZIP(), []int{12}
}

func (x *AFSDBRecord) GetSubtype() uint32 {
	if x != nil {
		return x.Subtype
	}
	return 0
}

func (x *AFSDBRecord) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

// NAPTR is a naming-authority pointer (RFC 3403).
type NAPTRRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         uint32                 `protobuf:"varint,1,opt,name=order,proto3" json:"order,omitempty"`
	Preference    uint32                 `protobuf:"varint,2,opt,name=preference,proto3" json:"preference,omitempty"`
	Flags         string                 `protobuf:"bytes,3,opt,name=flags,proto3" json:"flags,omitempty"`
	Service       string                 `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	Regexp        string                 `protobuf:"bytes,5,opt,name=regexp,proto3" json:"regexp,omitempty"`
	Replacement   string                 `protobuf:"bytes,6,opt,name=replacement,proto3" json:"replacement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NAPTRRecord) Reset() {
	*x = NAPTRRecord{}
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NAPTRRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NAPTRRecord) ProtoMessage() {}

func (x *NAPTRRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NAPTRRecord.ProtoReflect.Descriptor instead.
func (*NAPTRRecord) Descriptor() ([]byte, []int) {
	return file_proto_domainpb_dns_record_proto_rawDescGZIP(), []int{13}
}

func (x *NAPTRRecord) GetOrder() uint32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *NAPTRRecord) GetPreference() uint32 {
	if x != nil {
		return x.Preference
	}
	return 0
}

func (x *NAPTRRecord) GetFlags() string {
	if x != nil {
		return x.Flags
	}
	return ""
}

func (x *NAPTRRecord) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *NAPTRRecord) GetRegexp() string {
	if x != nil {
		return x.Regexp
	}
	return ""
}

func (x *NAPTRRecord) GetReplacement() string {
	if x != nil {
		return x.Replacement
	}
	return ""
}

// KX is a key-exchanger record (RFC 2230).
type KXRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Preference    uint32                 `protobuf:"varint,1,opt,name=preference,proto3" json:"preference,omitempty"`
	Exchanger     string                 `protobuf:"bytes,2,opt,name=exchanger,proto3" json:"exchanger,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KXRecord) Reset() {
	*x = KXRecord{}
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KXRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KXRecord) ProtoMessage() {}

func (x *KXRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KXRecord.ProtoReflect.Descriptor instead.
func (*KXRecord) Descriptor() ([]byte, []int) {
	return file_proto_domainpb_dns_record_proto_rawDescGZIP(), []int{14}
}

func (x *KXRecord) GetPreference() uint32 {
	if x != nil {
		return x.Preference
	}
	return 0
}

func (x *KXRecord) GetExchanger() string {
	if x != nil {
		return x.Exchanger
	}
	return ""
}

// SSHFP is an SSH-fingerprint record (RFC 4255). algorithm: 1=RSA,
// 2=DSA, 3=ECDSA, 4=Ed25519. fp_type: 1=SHA-1, 2=SHA-256.
type SSHFPRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algorithm     uint32                 `protobuf:"varint,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	FpType        uint32                 `protobuf:"varint,2,opt,name=fp_type,json=fpType,proto3" json:"fp_type,omitempty"`
	Fingerprint   []byte                 `protobuf:"bytes,3,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHFPRecord) Reset() {
	*x = SSHFPRecord{}
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHFPRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHFPRecord) ProtoMessage() {}

func (x *SSHFPRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHFPRecord.ProtoReflect.Descriptor instead.
func (*SSHFPRecord) Descriptor() ([]byte, []int) {
	return file_proto_domainpb_dns_record_proto_rawDescGZIP(), []int{15}
}

func (x *SSHFPRecord) GetAlgorithm() uint32 {
	if x != nil {
		return x.Algorithm
	}
	return 0
}

func (x *SSHFPRecord) GetFpType() uint32 {
	if x != nil {
		return x.FpType
	}
	return 0
}

func (x *SSHFPRecord) GetFingerprint() []byte {
	if x != nil {
		return x.Fingerprint
	}
	return nil
}

// SvcbParam is one SVCB/HTTPS service-parameter key-value pair
// (RFC 9460). Used by SVCBRecord and HTTPSRecord.
type SvcbParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           uint32                 `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SvcbParam) Reset() {
	*x = SvcbParam{}
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SvcbParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SvcbParam) ProtoMessage() {}

func (x *SvcbParam) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SvcbParam.ProtoReflect.Descriptor instead.
func (*SvcbParam) Descriptor() ([]byte, []int) {
	return file_proto_domainpb_dns_record_proto_rawDescGZIP(), []int{16}
}

func (x *SvcbParam) GetKey() uint32 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *SvcbParam) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// SVCB is a service-binding record (RFC 9460). priority 0 means
// AliasMode (target_name is an alias); any other value is ServiceMode.
// target_name "." means the SVCB owner name itself.
type SVCBRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Priority      uint32                 `protobuf:"varint,1,opt,name=priority,proto3" json:"priority,omitempty"`
	TargetName    string                 `protobuf:"bytes,2,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"`
	Params        []*SvcbParam           `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SVCBRecord) Reset() {
	*x = SVCBRecord{}
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SVCBRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SVCBRecord) ProtoMessage() {}

func (x *SVCBRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SVCBRecord.ProtoReflect.Descriptor instead.
func (*SVCBRecord) Descriptor() ([]byte, []int) {
	return file_proto_domainpb_dns_record_proto_rawDescGZIP(), []int{17}
}

func (x *SVCBRecord) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *SVCBRecord) GetTargetName() string {
	if x != nil {
		return x.TargetName
	}
	return ""
}

func (x *SVCBRecord) GetParams() []*SvcbParam {
	if x != nil {
		return x.Params
	}
	return nil
}

// HTTPS is an HTTPS service-binding record (RFC 9460). Same wire
// format as SVCB but a distinct RR type.
type HTTPSRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Priority      uint32                 `protobuf:"varint,1,opt,name=priority,proto3" json:"priority,omitempty"`
	TargetName    string                 `protobuf:"bytes,2,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"`
	Params        []*SvcbParam           `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPSRecord) Reset() {
	*x = HTTPSRecord{}
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPSRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPSRecord) ProtoMessage() {}

func (x *HTTPSRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPSRecord.ProtoReflect.Descriptor instead.
func (*HTTPSRecord) Descriptor() ([]byte, []int) {
	return file_proto_domainpb_dns_record_proto_rawDescGZIP(), []int{18}
}

func (x *HTTPSRecord) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *HTTPSRecord) GetTargetName() string {
	if x != nil {
		return x.TargetName
	}
	return ""
}

func (x *HTTPSRecord) GetParams() []*SvcbParam {
	if x != nil {
		return x.Params
	}
	return nil
}

// CAA is a certification-authority-authorization record (RFC 8659).
// tag is typically "issue", "issuewild", or "iodef". flags bit 7
// (0x01) is the issuer-critical flag.
type CAARecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flags         uint32                 `protobuf:"varint,1,opt,name=flags,proto3" json:"flags,omitempty"`
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CAARecord) Reset() {
	*x = CAARecord{}
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CAARecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CAARecord) ProtoMessage() {}

func (x *CAARecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CAARecord.ProtoReflect.Descriptor instead.
func (*CAARecord) Descriptor() ([]byte, []int) {
	return file_proto_domainpb_dns_record_proto_rawDescGZIP(), []int{19}
}

func (x *CAARecord) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *CAARecord) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *CAARecord) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// URI is a URI record (RFC 7553). target is the full URI string
// (e.g. "mailto:admin@example.com" or "tel:+15551234567").
type URIRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Priority      uint32                 `protobuf:"varint,1,opt,name=priority,proto3" json:"priority,omitempty"`
	Weight        uint32                 `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URIRecord) Reset() {
	*x = URIRecord{}
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URIRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URIRecord) ProtoMessage() {}

func (x *URIRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domainpb_dns_record_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URIRecord.ProtoReflect.Descriptor instead.
func (*URIRecord) Descriptor() ([]byte, []int) {
	return file_proto_domainpb_dns_record_proto_rawDescGZIP(), []int{20}
}

func (x *URIRecord) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *URIRecord) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *URIRecord) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

var File_proto_domainpb_dns_record_proto protoreflect.FileDescriptor

const file_proto_domainpb_dns_record_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/domainpb/dns_record.proto\x12\x06domain\x1a\x1bproto/domainpb/domain.proto\"\xaf\a\n" +
	"\tDNSRecord\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.domain.DNSRecordTypeR\x04type\x12&\n" +
	"\x06target\x18\x02 \x01(\v2\x0e.domain.DomainR\x06target\x12#\n" +
	"\x05class\x18\x03 \x01(\x0e2\r.domain.ClassR\x05class\x12\x1f\n" +
	"\vttl_seconds\x18\x04 \x01(\x05R\n" +
	"ttlSeconds\x12\x1f\n" +
	"\x01a\x18\x05 \x01(\v2\x0f.domain.ARecordH\x00R\x01a\x12(\n" +
	"\x04aaaa\x18\x06 \x01(\v2\x12.domain.AAAARecordH\x00R\x04aaaa\x12+\n" +
	"\x05cname\x18\a \x01(\v2\x13.domain.CNAMERecordH\x00R\x05cname\x12+\n" +
	"\x05dname\x18\b \x01(\v2\x13.domain.DNAMERecordH\x00R\x05dname\x12\"\n" +
	"\x02ns\x18\t \x01(\v2\x10.domain.NSRecordH\x00R\x02ns\x12\"\n" +
	"\x02mx\x18\n" +
	" \x01(\v2\x10.domain.MXRecordH\x00R\x02mx\x12%\n" +
	"\x03txt\x18\v \x01(\v2\x11.domain.TXTRecordH\x00R\x03txt\x12%\n" +
	"\x03soa\x18\f \x01(\v2\x11.domain.SOARecordH\x00R\x03soa\x12%\n" +
	"\x03loc\x18\r \x01(\v2\x11.domain.LOCRecordH\x00R\x03loc\x12+\n" +
	"\x05hinfo\x18\x0e \x01(\v2\x13.domain.HINFORecordH\x00R\x05hinfo\x12\"\n" +
	"\x02rp\x18\x0f \x01(\v2\x10.domain.RPRecordH\x00R\x02rp\x12+\n" +
	"\x05afsdb\x18\x10 \x01(\v2\x13.domain.AFSDBRecordH\x00R\x05afsdb\x12+\n" +
	"\x05naptr\x18\x11 \x01(\v2\x13.domain.NAPTRRecordH\x00R\x05naptr\x12\"\n" +
	"\x02kx\x18\x12 \x01(\v2\x10.domain.KXRecordH\x00R\x02kx\x12+\n" +
	"\x05sshfp\x18\x13 \x01(\v2\x13.domain.SSHFPRecordH\x00R\x05sshfp\x12(\n" +
	"\x04svcb\x18\x14 \x01(\v2\x12.domain.SVCBRecordH\x00R\x04svcb\x12+\n" +
	"\x05https\x18\x15 \x01(\v2\x13.domain.HTTPSRecordH\x00R\x05https\x12%\n" +
	"\x03caa\x18\x16 \x01(\v2\x11.domain.CAARecordH\x00R\x03caa\x12%\n" +
	"\x03uri\x18\x17 \x01(\v2\x11.domain.URIRecordH\x00R\x03uriB\x06\n" +
	"\x04body\"\x1d\n" +
	"\aARecord\x12\x12\n" +
	"\x04ipv4\x18\x01 \x01(\fR\x04ipv4\" \n" +
	"\n" +
	"AAAARecord\x12\x12\n" +
	"\x04ipv6\x18\x01 \x01(\fR\x04ipv6\"%\n" +
	"\vCNAMERecord\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\"%\n" +
	"\vDNAMERecord\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\"\x1e\n" +
	"\bNSRecord\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\"2\n" +
	"\bMXRecord\x12\x12\n" +
	"\x04pref\x18\x01 \x01(\rR\x04pref\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\"%\n" +
	"\tTXTRecord\x12\x18\n" +
	"\astrings\x18\x01 \x03(\tR\astrings\"\xa8\x01\n" +
	"\tSOARecord\x12\x0e\n" +
	"\x02ns\x18\x01 \x01(\tR\x02ns\x12\x12\n" +
	"\x04mbox\x18\x02 \x01(\tR\x04mbox\x12\x16\n" +
	"\x06serial\x18\x03 \x01(\rR\x06serial\x12\x18\n" +
	"\arefresh\x18\x04 \x01(\rR\arefresh\x12\x14\n" +
	"\x05retry\x18\x05 \x01(\rR\x05retry\x12\x16\n" +
	"\x06expire\x18\x06 \x01(\rR\x06expire\x12\x17\n" +
	"\amin_ttl\x18\a \x01(\rR\x06minTtl\"\xc7\x01\n" +
	"\tLOCRecord\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\x12\x1b\n" +
	"\thoriz_pre\x18\x03 \x01(\rR\bhorizPre\x12\x19\n" +
	"\bvert_pre\x18\x04 \x01(\rR\avertPre\x12\x1a\n" +
	"\blatitude\x18\x05 \x01(\rR\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x06 \x01(\rR\tlongitude\x12\x1a\n" +
	"\baltitude\x18\a \x01(\rR\baltitude\"/\n" +
	"\vHINFORecord\x12\x10\n" +
	"\x03cpu\x18\x01 \x01(\tR\x03cpu\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\"0\n" +
	"\bRPRecord\x12\x12\n" +
	"\x04mbox\x18\x01 \x01(\tR\x04mbox\x12\x10\n" +
	"\x03txt\x18\x02 \x01(\tR\x03txt\"C\n" +
	"\vAFSDBRecord\x12\x18\n" +
	"\asubtype\x18\x01 \x01(\rR\asubtype\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\"\xad\x01\n" +
	"\vNAPTRRecord\x12\x14\n" +
	"\x05order\x18\x01 \x01(\rR\x05order\x12\x1e\n" +
	"\n" +
	"preference\x18\x02 \x01(\rR\n" +
	"preference\x12\x14\n" +
	"\x05flags\x18\x03 \x01(\tR\x05flags\x12\x18\n" +
	"\aservice\x18\x04 \x01(\tR\aservice\x12\x16\n" +
	"\x06regexp\x18\x05 \x01(\tR\x06regexp\x12 \n" +
	"\vreplacement\x18\x06 \x01(\tR\vreplacement\"H\n" +
	"\bKXRecord\x12\x1e\n" +
	"\n" +
	"preference\x18\x01 \x01(\rR\n" +
	"preference\x12\x1c\n" +
	"\texchanger\x18\x02 \x01(\tR\texchanger\"f\n" +
	"\vSSHFPRecord\x12\x1c\n" +
	"\talgorithm\x18\x01 \x01(\rR\talgorithm\x12\x17\n" +
	"\afp_type\x18\x02 \x01(\rR\x06fpType\x12 \n" +
	"\vfingerprint\x18\x03 \x01(\fR\vfingerprint\"3\n" +
	"\tSvcbParam\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"t\n" +
	"\n" +
	"SVCBRecord\x12\x1a\n" +
	"\bpriority\x18\x01 \x01(\rR\bpriority\x12\x1f\n" +
	"\vtarget_name\x18\x02 \x01(\tR\n" +
	"targetName\x12)\n" +
	"\x06params\x18\x03 \x03(\v2\x11.domain.SvcbParamR\x06params\"u\n" +
	"\vHTTPSRecord\x12\x1a\n" +
	"\bpriority\x18\x01 \x01(\rR\bpriority\x12\x1f\n" +
	"\vtarget_name\x18\x02 \x01(\tR\n" +
	"targetName\x12)\n" +
	"\x06params\x18\x03 \x03(\v2\x11.domain.SvcbParamR\x06params\"I\n" +
	"\tCAARecord\x12\x14\n" +
	"\x05flags\x18\x01 \x01(\rR\x05flags\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"W\n" +
	"\tURIRecord\x12\x1a\n" +
	"\bpriority\x18\x01 \x01(\rR\bpriority\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\rR\x06weight\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target*\xb4\x04\n" +
	"\rDNSRecordType\x12\x12\n" +
	"\x0eRECORD_UNKNOWN\x10\x00\x12\x05\n" +
	"\x01A\x10\x01\x12\x06\n" +
	"\x02NS\x10\x02\x12\t\n" +
	"\x05CNAME\x10\x05\x12\a\n" +
	"\x03SOA\x10\x06\x12\a\n" +
	"\x03PTR\x10\f\x12\t\n" +
	"\x05HINFO\x10\r\x12\x06\n" +
	"\x02MX\x10\x0f\x12\a\n" +
	"\x03TXT\x10\x10\x12\x06\n" +
	"\x02RP\x10\x11\x12\t\n" +
	"\x05AFSDB\x10\x12\x12\a\n" +
	"\x03SIG\x10\x18\x12\a\n" +
	"\x03KEY\x10\x19\x12\b\n" +
	"\x04AAAA\x10\x1c\x12\a\n" +
	"\x03LOC\x10\x1d\x12\a\n" +
	"\x03SRV\x10!\x12\t\n" +
	"\x05NAPTR\x10#\x12\x06\n" +
	"\x02KX\x10$\x12\b\n" +
	"\x04CERT\x10%\x12\t\n" +
	"\x05DNAME\x10'\x12\a\n" +
	"\x03OPT\x10)\x12\a\n" +
	"\x03APL\x10*\x12\x06\n" +
	"\x02DS\x10+\x12\t\n" +
	"\x05SSHFP\x10,\x12\f\n" +
	"\bIPSECKEY\x10-\x12\t\n" +
	"\x05RRSIG\x10.\x12\b\n" +
	"\x04NSEC\x10/\x12\n" +
	"\n" +
	"\x06DNSKEY\x100\x12\t\n" +
	"\x05DHCID\x101\x12\t\n" +
	"\x05NSEC3\x102\x12\x0e\n" +
	"\n" +
	"NSEC3PARAM\x103\x12\b\n" +
	"\x04TLSA\x104\x12\n" +
	"\n" +
	"\x06SMIMEA\x105\x12\a\n" +
	"\x03HIP\x107\x12\a\n" +
	"\x03CDS\x10;\x12\v\n" +
	"\aCDNSKEY\x10<\x12\x0e\n" +
	"\n" +
	"OPENPGPKEY\x10=\x12\t\n" +
	"\x05CSYNC\x10>\x12\n" +
	"\n" +
	"\x06ZONEMD\x10?\x12\b\n" +
	"\x04SVCB\x10@\x12\t\n" +
	"\x05HTTPS\x10A\x12\t\n" +
	"\x05EUI48\x10l\x12\t\n" +
	"\x05EUI64\x10m\x12\t\n" +
	"\x04TKEY\x10\xf9\x01\x12\t\n" +
	"\x04TSIG\x10\xfa\x01\x12\t\n" +
	"\x04IXFR\x10\xfb\x01\x12\t\n" +
	"\x04AXFR\x10\xfc\x01\x12\b\n" +
	"\x03ANY\x10\xff\x01\x12\b\n" +
	"\x03URI\x10\x80\x02\x12\b\n" +
	"\x03CAA\x10\x81\x02\x12\b\n" +
	"\x02TA\x10\x80\x80\x02\x12\t\n" +
	"\x03DLV\x10\x81\x80\x02*(\n" +
	"\x05Class\x12\x11\n" +
	"\rCLASS_UNKNOWN\x10\x00\x12\f\n" +
	"\bInternet\x10\x01B=Z;github.com/accretional/proto-domain/proto/domainpb;domainpbb\x06proto3"

var (
	file_proto_domainpb_dns_record_proto_rawDescOnce sync.Once
	file_proto_domainpb_dns_record_proto_rawDescData []byte
)

func file_proto_domainpb_dns_record_proto_rawDescGZIP() []byte {
	file_proto_domainpb_dns_record_proto_rawDescOnce.Do(func() {
		file_proto_domainpb_dns_record_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_domainpb_dns_record_proto_rawDesc), len(file_proto_domainpb_dns_record_proto_rawDesc)))
	})
	return file_proto_domainpb_dns_record_proto_rawDescData
}

var file_proto_domainpb_dns_record_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_domainpb_dns_record_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_domainpb_dns_record_proto_goTypes = []any{
	(DNSRecordType)(0),  // 0: domain.DNSRecordType
	(Class)(0),          // 1: domain.Class
	(*DNSRecord)(nil),   // 2: domain.DNSRecord
	(*ARecord)(nil),     // 3: domain.ARecord
	(*AAAARecord)(nil),  // 4: domain.AAAARecord
	(*CNAMERecord)(nil), // 5: domain.CNAMERecord
	(*DNAMERecord)(nil), // 6: domain.DNAMERecord
	(*NSRecord)(nil),    // 7: domain.NSRecord
	(*MXRecord)(nil),    // 8: domain.MXRecord
	(*TXTRecord)(nil),   // 9: domain.TXTRecord
	(*SOARecord)(nil),   // 10: domain.SOARecord
	(*LOCRecord)(nil),   // 11: domain.LOCRecord
	(*HINFORecord)(nil), // 12: domain.HINFORecord
	(*RPRecord)(nil),    // 13: domain.RPRecord
	(*AFSDBRecord)(nil), // 14: domain.AFSDBRecord
	(*NAPTRRecord)(nil), // 15: domain.NAPTRRecord
	(*KXRecord)(nil),    // 16: domain.KXRecord
	(*SSHFPRecord)(nil), // 17: domain.SSHFPRecord
	(*SvcbParam)(nil),   // 18: domain.SvcbParam
	(*SVCBRecord)(nil),  // 19: domain.SVCBRecord
	(*HTTPSRecord)(nil), // 20: domain.HTTPSRecord
	(*CAARecord)(nil),   // 21: domain.CAARecord
	(*URIRecord)(nil),   // 22: domain.URIRecord
	(*Domain)(nil),      // 23: domain.Domain
}
var file_proto_domainpb_dns_record_proto_depIdxs = []int32{
	0,  // 0: domain.DNSRecord.type:type_name -> domain.DNSRecordType
	23, // 1: domain.DNSRecord.target:type_name -> domain.Domain
	1,  // 2: domain.DNSRecord.class:type_name -> domain.Class
	3,  // 3: domain.DNSRecord.a:type_name -> domain.ARecord
	4,  // 4: domain.DNSRecord.aaaa:type_name -> domain.AAAARecord
	5,  // 5: domain.DNSRecord.cname:type_name -> domain.CNAMERecord
	6,  // 6: domain.DNSRecord.dname:type_name -> domain.DNAMERecord
	7,  // 7: domain.DNSRecord.ns:type_name -> domain.NSRecord
	8,  // 8: domain.DNSRecord.mx:type_name -> domain.MXRecord
	9,  // 9: domain.DNSRecord.txt:type_name -> domain.TXTRecord
	10, // 10: domain.DNSRecord.soa:type_name -> domain.SOARecord
	11, // 11: domain.DNSRecord.loc:type_name -> domain.LOCRecord
	12, // 12: domain.DNSRecord.hinfo:type_name -> domain.HINFORecord
	13, // 13: domain.DNSRecord.rp:type_name -> domain.RPRecord
	14, // 14: domain.DNSRecord.afsdb:type_name -> domain.AFSDBRecord
	15, // 15: domain.DNSRecord.naptr:type_name -> domain.NAPTRRecord
	16, // 16: domain.DNSRecord.kx:type_name -> domain.KXRecord
	17, // 17: domain.DNSRecord.sshfp:type_name -> domain.SSHFPRecord
	19, // 18: domain.DNSRecord.svcb:type_name -> domain.SVCBRecord
	20, // 19: domain.DNSRecord.https:type_name -> domain.HTTPSRecord
	21, // 20: domain.DNSRecord.caa:type_name -> domain.CAARecord
	22, // 21: domain.DNSRecord.uri:type_name -> domain.URIRecord
	18, // 22: domain.SVCBRecord.params:type_name -> domain.SvcbParam
	18, // 23: domain.HTTPSRecord.params:type_name -> domain.SvcbParam
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_proto_domainpb_dns_record_proto_init() }
func file_proto_domainpb_dns_record_proto_init() {
	if File_proto_domainpb_dns_record_proto != nil {
		return
	}
	file_proto_domainpb_domain_proto_init()
	file_proto_domainpb_dns_record_proto_msgTypes[0].OneofWrappers = []any{
		(*DNSRecord_A)(nil),
		(*DNSRecord_Aaaa)(nil),
		(*DNSRecord_Cname)(nil),
		(*DNSRecord_Dname)(nil),
		(*DNSRecord_Ns)(nil),
		(*DNSRecord_Mx)(nil),
		(*DNSRecord_Txt)(nil),
		(*DNSRecord_Soa)(nil),
		(*DNSRecord_Loc)(nil),
		(*DNSRecord_Hinfo)(nil),
		(*DNSRecord_Rp)(nil),
		(*DNSRecord_Afsdb)(nil),
		(*DNSRecord_Naptr)(nil),
		(*DNSRecord_Kx)(nil),
		(*DNSRecord_Sshfp)(nil),
		(*DNSRecord_Svcb)(nil),
		(*DNSRecord_Https)(nil),
		(*DNSRecord_Caa)(nil),
		(*DNSRecord_Uri)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_domainpb_dns_record_proto_rawDesc), len(file_proto_domainpb_dns_record_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_domainpb_dns_record_proto_goTypes,
		DependencyIndexes: file_proto_domainpb_dns_record_proto_depIdxs,
		EnumInfos:         file_proto_domainpb_dns_record_proto_enumTypes,
		MessageInfos:      file_proto_domainpb_dns_record_proto_msgTypes,
	}.Build()
	File_proto_domainpb_dns_record_proto = out.File
	file_proto_domainpb_dns_record_proto_goTypes = nil
	file_proto_domainpb_dns_record_proto_depIdxs = nil
}
