// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/domainpb/domain.proto

package domainpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InternetTLD enumerates well-known top-level domains. Only entries that
// have explicit support here get a stable ID; everything else is carried
// as a string in the surrounding TLD.custom field.
type InternetTLD int32

const (
	InternetTLD_None InternetTLD = 0
	InternetTLD_COM  InternetTLD = 1 // TODO bring em all in
)

// Enum value maps for InternetTLD.
var (
	InternetTLD_name = map[int32]string{
		0: "None",
		1: "COM",
	}
	InternetTLD_value = map[string]int32{
		"None": 0,
		"COM":  1,
	}
)

func (x InternetTLD) Enum() *InternetTLD {
	p := new(InternetTLD)
	*p = x
	return p
}

func (x InternetTLD) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InternetTLD) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_domainpb_domain_proto_enumTypes[0].Descriptor()
}

func (InternetTLD) Type() protoreflect.EnumType {
	return &file_proto_domainpb_domain_proto_enumTypes[0]
}

func (x InternetTLD) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InternetTLD.Descriptor instead.
func (InternetTLD) EnumDescriptor() ([]byte, []int) {
	return file_proto_domainpb_domain_proto_rawDescGZIP(), []int{0}
}

// TLD is the rightmost label in a domain name. Either matched against the
// known InternetTLD enum or carried verbatim as a string.
type TLD struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Format:
	//
	//	*TLD_Internet
	//	*TLD_Custom
	Format        isTLD_Format `protobuf_oneof:"format"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLD) Reset() {
	*x = TLD{}
	mi := &file_proto_domainpb_domain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLD) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLD) ProtoMessage() {}

func (x *TLD) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domainpb_domain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLD.ProtoReflect.Descriptor instead.
func (*TLD) Descriptor() ([]byte, []int) {
	return file_proto_domainpb_domain_proto_rawDescGZIP(), []int{0}
}

func (x *TLD) GetFormat() isTLD_Format {
	if x != nil {
		return x.Format
	}
	return nil
}

func (x *TLD) GetInternet() InternetTLD {
	if x != nil {
		if x, ok := x.Format.(*TLD_Internet); ok {
			return x.Internet
		}
	}
	return InternetTLD_None
}

func (x *TLD) GetCustom() string {
	if x != nil {
		if x, ok := x.Format.(*TLD_Custom); ok {
			return x.Custom
		}
	}
	return ""
}

type isTLD_Format interface {
	isTLD_Format()
}

type TLD_Internet struct {
	Internet InternetTLD `protobuf:"varint,1,opt,name=internet,proto3,enum=domain.InternetTLD,oneof"`
}

type TLD_Custom struct {
	Custom string `protobuf:"bytes,2,opt,name=custom,proto3,oneof"`
}

func (*TLD_Internet) isTLD_Format() {}

func (*TLD_Custom) isTLD_Format() {}

// Domain is a DNS domain name in canonical (RFC 1035 / RFC 5890) form.
//
// `hostname` is the original printed string (lowercased, dot-separated,
// no trailing dot unless the source was an FQDN).
//
// `labels` carries the per-label decomposition in left-to-right order
// EXCLUDING the rightmost (TLD) label — that one rides in `tld`.
//
// Round-trip rule: printing the typed Domain back to a string yields
// `strings.Join(append(labels, tldString(tld)), ".")` plus an optional
// trailing "." when the original source was a fully qualified domain
// name (see `fully_qualified`).
type Domain struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Hostname string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Labels   []string               `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"`
	Tld      *TLD                   `protobuf:"bytes,3,opt,name=tld,proto3" json:"tld,omitempty"`
	// True when the printed source ended with "." (RFC 1034 absolute form).
	FullyQualified bool `protobuf:"varint,4,opt,name=fully_qualified,json=fullyQualified,proto3" json:"fully_qualified,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Domain) Reset() {
	*x = Domain{}
	mi := &file_proto_domainpb_domain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Domain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Domain) ProtoMessage() {}

func (x *Domain) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domainpb_domain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Domain.ProtoReflect.Descriptor instead.
func (*Domain) Descriptor() ([]byte, []int) {
	return file_proto_domainpb_domain_proto_rawDescGZIP(), []int{1}
}

func (x *Domain) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Domain) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Domain) GetTld() *TLD {
	if x != nil {
		return x.Tld
	}
	return nil
}

func (x *Domain) GetFullyQualified() bool {
	if x != nil {
		return x.FullyQualified
	}
	return false
}

var File_proto_domainpb_domain_proto protoreflect.FileDescriptor

const file_proto_domainpb_domain_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/domainpb/domain.proto\x12\x06domain\"\\\n" +
	"\x03TLD\x121\n" +
	"\binternet\x18\x01 \x01(\x0e2\x13.domain.InternetTLDH\x00R\binternet\x12\x18\n" +
	"\x06custom\x18\x02 \x01(\tH\x00R\x06customB\b\n" +
	"\x06format\"\x84\x01\n" +
	"\x06Domain\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x16\n" +
	"\x06labels\x18\x02 \x03(\tR\x06labels\x12\x1d\n" +
	"\x03tld\x18\x03 \x01(\v2\v.domain.TLDR\x03tld\x12'\n" +
	"\x0ffully_qualified\x18\x04 \x01(\bR\x0efullyQualified* \n" +
	"\vInternetTLD\x12\b\n" +
	"\x04None\x10\x00\x12\a\n" +
	"\x03COM\x10\x01B=Z;github.com/accretional/proto-domain/proto/domainpb;domainpbb\x06proto3"

var (
	file_proto_domainpb_domain_proto_rawDescOnce sync.Once
	file_proto_domainpb_domain_proto_rawDescData []byte
)

func file_proto_domainpb_domain_proto_rawDescGZIP() []byte {
	file_proto_domainpb_domain_proto_rawDescOnce.Do(func() {
		file_proto_domainpb_domain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_domainpb_domain_proto_rawDesc), len(file_proto_domainpb_domain_proto_rawDesc)))
	})
	return file_proto_domainpb_domain_proto_rawDescData
}

var file_proto_domainpb_domain_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_domainpb_domain_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_domainpb_domain_proto_goTypes = []any{
	(InternetTLD)(0), // 0: domain.InternetTLD
	(*TLD)(nil),      // 1: domain.TLD
	(*Domain)(nil),   // 2: domain.Domain
}
var file_proto_domainpb_domain_proto_depIdxs = []int32{
	0, // 0: domain.TLD.internet:type_name -> domain.InternetTLD
	1, // 1: domain.Domain.tld:type_name -> domain.TLD
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_domainpb_domain_proto_init() }
func file_proto_domainpb_domain_proto_init() {
	if File_proto_domainpb_domain_proto != nil {
		return
	}
	file_proto_domainpb_domain_proto_msgTypes[0].OneofWrappers = []any{
		(*TLD_Internet)(nil),
		(*TLD_Custom)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_domainpb_domain_proto_rawDesc), len(file_proto_domainpb_domain_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_domainpb_domain_proto_goTypes,
		DependencyIndexes: file_proto_domainpb_domain_proto_depIdxs,
		EnumInfos:         file_proto_domainpb_domain_proto_enumTypes,
		MessageInfos:      file_proto_domainpb_domain_proto_msgTypes,
	}.Build()
	File_proto_domainpb_domain_proto = out.File
	file_proto_domainpb_domain_proto_goTypes = nil
	file_proto_domainpb_domain_proto_depIdxs = nil
}
