// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/domainpb/rdap.proto

package domainpb

import (
	ippb "github.com/accretional/proto-ip/proto/ippb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RDAPNameserver is a nameserver object from an RDAP domain response
// (RFC 7483 §10.2.2). Glue addresses are included when present.
type RDAPNameserver struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Handle string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	// LDH (letters-digits-hyphens) form of the nameserver hostname.
	LdhName string `protobuf:"bytes,2,opt,name=ldh_name,json=ldhName,proto3" json:"ldh_name,omitempty"`
	// Unicode/IDN form, populated only for internationalised names.
	UnicodeName string            `protobuf:"bytes,3,opt,name=unicode_name,json=unicodeName,proto3" json:"unicode_name,omitempty"`
	Status      []ippb.RDAPStatus `protobuf:"varint,4,rep,packed,name=status,proto3,enum=ip.RDAPStatus" json:"status,omitempty"`
	Links       []string          `protobuf:"bytes,5,rep,name=links,proto3" json:"links,omitempty"`
	// Glue IPv4 addresses (text form), when returned by the registry.
	Ipv4Addresses []string `protobuf:"bytes,6,rep,name=ipv4_addresses,json=ipv4Addresses,proto3" json:"ipv4_addresses,omitempty"`
	// Glue IPv6 addresses (text form), when returned by the registry.
	Ipv6Addresses []string `protobuf:"bytes,7,rep,name=ipv6_addresses,json=ipv6Addresses,proto3" json:"ipv6_addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RDAPNameserver) Reset() {
	*x = RDAPNameserver{}
	mi := &file_proto_domainpb_rdap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RDAPNameserver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RDAPNameserver) ProtoMessage() {}

func (x *RDAPNameserver) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domainpb_rdap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RDAPNameserver.ProtoReflect.Descriptor instead.
func (*RDAPNameserver) Descriptor() ([]byte, []int) {
	return file_proto_domainpb_rdap_proto_rawDescGZIP(), []int{0}
}

func (x *RDAPNameserver) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *RDAPNameserver) GetLdhName() string {
	if x != nil {
		return x.LdhName
	}
	return ""
}

func (x *RDAPNameserver) GetUnicodeName() string {
	if x != nil {
		return x.UnicodeName
	}
	return ""
}

func (x *RDAPNameserver) GetStatus() []ippb.RDAPStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *RDAPNameserver) GetLinks() []string {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *RDAPNameserver) GetIpv4Addresses() []string {
	if x != nil {
		return x.Ipv4Addresses
	}
	return nil
}

func (x *RDAPNameserver) GetIpv6Addresses() []string {
	if x != nil {
		return x.Ipv6Addresses
	}
	return nil
}

// RDAPDSData is one DS record from the secureDNS.dsData array
// (RFC 7483 §10.2.5, RFC 4034 §5).
type RDAPDSData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyTag        uint32                 `protobuf:"varint,1,opt,name=key_tag,json=keyTag,proto3" json:"key_tag,omitempty"`
	Algorithm     uint32                 `protobuf:"varint,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	DigestType    uint32                 `protobuf:"varint,3,opt,name=digest_type,json=digestType,proto3" json:"digest_type,omitempty"`
	Digest        string                 `protobuf:"bytes,4,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RDAPDSData) Reset() {
	*x = RDAPDSData{}
	mi := &file_proto_domainpb_rdap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RDAPDSData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RDAPDSData) ProtoMessage() {}

func (x *RDAPDSData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domainpb_rdap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RDAPDSData.ProtoReflect.Descriptor instead.
func (*RDAPDSData) Descriptor() ([]byte, []int) {
	return file_proto_domainpb_rdap_proto_rawDescGZIP(), []int{1}
}

func (x *RDAPDSData) GetKeyTag() uint32 {
	if x != nil {
		return x.KeyTag
	}
	return 0
}

func (x *RDAPDSData) GetAlgorithm() uint32 {
	if x != nil {
		return x.Algorithm
	}
	return 0
}

func (x *RDAPDSData) GetDigestType() uint32 {
	if x != nil {
		return x.DigestType
	}
	return 0
}

func (x *RDAPDSData) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

// RDAPKeyData is one DNSKEY record from the secureDNS.keyData array
// (RFC 7483 §10.2.5, RFC 4034 §2).
type RDAPKeyData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flags         uint32                 `protobuf:"varint,1,opt,name=flags,proto3" json:"flags,omitempty"`
	Protocol      uint32                 `protobuf:"varint,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Algorithm     uint32                 `protobuf:"varint,3,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	PublicKey     string                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RDAPKeyData) Reset() {
	*x = RDAPKeyData{}
	mi := &file_proto_domainpb_rdap_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RDAPKeyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RDAPKeyData) ProtoMessage() {}

func (x *RDAPKeyData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domainpb_rdap_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RDAPKeyData.ProtoReflect.Descriptor instead.
func (*RDAPKeyData) Descriptor() ([]byte, []int) {
	return file_proto_domainpb_rdap_proto_rawDescGZIP(), []int{2}
}

func (x *RDAPKeyData) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *RDAPKeyData) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *RDAPKeyData) GetAlgorithm() uint32 {
	if x != nil {
		return x.Algorithm
	}
	return 0
}

func (x *RDAPKeyData) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

// RDAPSecureDNS carries the secureDNS object from an RDAP domain response
// (RFC 7483 §10.2.5). All five RIRs and major gTLD registries populate this.
type RDAPSecureDNS struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	DelegationSigned       bool                   `protobuf:"varint,1,opt,name=delegation_signed,json=delegationSigned,proto3" json:"delegation_signed,omitempty"`
	ZoneSigned             bool                   `protobuf:"varint,2,opt,name=zone_signed,json=zoneSigned,proto3" json:"zone_signed,omitempty"`
	CheckSignatureValidity bool                   `protobuf:"varint,3,opt,name=check_signature_validity,json=checkSignatureValidity,proto3" json:"check_signature_validity,omitempty"`
	MaxSigLife             uint32                 `protobuf:"varint,4,opt,name=max_sig_life,json=maxSigLife,proto3" json:"max_sig_life,omitempty"`
	DsData                 []*RDAPDSData          `protobuf:"bytes,5,rep,name=ds_data,json=dsData,proto3" json:"ds_data,omitempty"`
	KeyData                []*RDAPKeyData         `protobuf:"bytes,6,rep,name=key_data,json=keyData,proto3" json:"key_data,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RDAPSecureDNS) Reset() {
	*x = RDAPSecureDNS{}
	mi := &file_proto_domainpb_rdap_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RDAPSecureDNS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RDAPSecureDNS) ProtoMessage() {}

func (x *RDAPSecureDNS) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domainpb_rdap_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RDAPSecureDNS.ProtoReflect.Descriptor instead.
func (*RDAPSecureDNS) Descriptor() ([]byte, []int) {
	return file_proto_domainpb_rdap_proto_rawDescGZIP(), []int{3}
}

func (x *RDAPSecureDNS) GetDelegationSigned() bool {
	if x != nil {
		return x.DelegationSigned
	}
	return false
}

func (x *RDAPSecureDNS) GetZoneSigned() bool {
	if x != nil {
		return x.ZoneSigned
	}
	return false
}

func (x *RDAPSecureDNS) GetCheckSignatureValidity() bool {
	if x != nil {
		return x.CheckSignatureValidity
	}
	return false
}

func (x *RDAPSecureDNS) GetMaxSigLife() uint32 {
	if x != nil {
		return x.MaxSigLife
	}
	return 0
}

func (x *RDAPSecureDNS) GetDsData() []*RDAPDSData {
	if x != nil {
		return x.DsData
	}
	return nil
}

func (x *RDAPSecureDNS) GetKeyData() []*RDAPKeyData {
	if x != nil {
		return x.KeyData
	}
	return nil
}

// RDAPDomain is the domain registration object returned by an RDAP registry.
// It corresponds to the "domain" objectClassName from RFC 7483 §7.3.
type RDAPDomain struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Registry handle (e.g. "2138514_DOMAIN_COM-VRSN").
	Handle string `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	// LDH form of the domain name as returned by the registry.
	LdhName string `protobuf:"bytes,2,opt,name=ldh_name,json=ldhName,proto3" json:"ldh_name,omitempty"`
	// Unicode/IDN form, populated only for internationalised names.
	UnicodeName string             `protobuf:"bytes,3,opt,name=unicode_name,json=unicodeName,proto3" json:"unicode_name,omitempty"`
	Nameservers []*RDAPNameserver  `protobuf:"bytes,4,rep,name=nameservers,proto3" json:"nameservers,omitempty"`
	SecureDns   *RDAPSecureDNS     `protobuf:"bytes,5,opt,name=secure_dns,json=secureDns,proto3" json:"secure_dns,omitempty"`
	Status      []ippb.RDAPStatus  `protobuf:"varint,6,rep,packed,name=status,proto3,enum=ip.RDAPStatus" json:"status,omitempty"`
	Entities    []*ippb.RDAPEntity `protobuf:"bytes,7,rep,name=entities,proto3" json:"entities,omitempty"`
	Events      []*ippb.RDAPEvent  `protobuf:"bytes,8,rep,name=events,proto3" json:"events,omitempty"`
	// Self / alternate link hrefs from the RDAP links array.
	Links []string `protobuf:"bytes,9,rep,name=links,proto3" json:"links,omitempty"`
	// Base URL of the RDAP server that was queried.
	RdapServer string `protobuf:"bytes,10,opt,name=rdap_server,json=rdapServer,proto3" json:"rdap_server,omitempty"`
	// RDAP conformance extensions declared by the server.
	RdapConformance []string `protobuf:"bytes,11,rep,name=rdap_conformance,json=rdapConformance,proto3" json:"rdap_conformance,omitempty"`
	// WHOIS server hostname from the port43 field, if present.
	Port43        string `protobuf:"bytes,12,opt,name=port43,proto3" json:"port43,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RDAPDomain) Reset() {
	*x = RDAPDomain{}
	mi := &file_proto_domainpb_rdap_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RDAPDomain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RDAPDomain) ProtoMessage() {}

func (x *RDAPDomain) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domainpb_rdap_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RDAPDomain.ProtoReflect.Descriptor instead.
func (*RDAPDomain) Descriptor() ([]byte, []int) {
	return file_proto_domainpb_rdap_proto_rawDescGZIP(), []int{4}
}

func (x *RDAPDomain) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *RDAPDomain) GetLdhName() string {
	if x != nil {
		return x.LdhName
	}
	return ""
}

func (x *RDAPDomain) GetUnicodeName() string {
	if x != nil {
		return x.UnicodeName
	}
	return ""
}

func (x *RDAPDomain) GetNameservers() []*RDAPNameserver {
	if x != nil {
		return x.Nameservers
	}
	return nil
}

func (x *RDAPDomain) GetSecureDns() *RDAPSecureDNS {
	if x != nil {
		return x.SecureDns
	}
	return nil
}

func (x *RDAPDomain) GetStatus() []ippb.RDAPStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *RDAPDomain) GetEntities() []*ippb.RDAPEntity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *RDAPDomain) GetEvents() []*ippb.RDAPEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *RDAPDomain) GetLinks() []string {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *RDAPDomain) GetRdapServer() string {
	if x != nil {
		return x.RdapServer
	}
	return ""
}

func (x *RDAPDomain) GetRdapConformance() []string {
	if x != nil {
		return x.RdapConformance
	}
	return nil
}

func (x *RDAPDomain) GetPort43() string {
	if x != nil {
		return x.Port43
	}
	return ""
}

// RDAPDomainResponse wraps the parsed domain registration record.
type RDAPDomainResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Domain *RDAPDomain            `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	// Full RDAP JSON response body, preserved for callers that need
	// fields not modelled in RDAPDomain.
	RawJson       string `protobuf:"bytes,2,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RDAPDomainResponse) Reset() {
	*x = RDAPDomainResponse{}
	mi := &file_proto_domainpb_rdap_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RDAPDomainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RDAPDomainResponse) ProtoMessage() {}

func (x *RDAPDomainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domainpb_rdap_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RDAPDomainResponse.ProtoReflect.Descriptor instead.
func (*RDAPDomainResponse) Descriptor() ([]byte, []int) {
	return file_proto_domainpb_rdap_proto_rawDescGZIP(), []int{5}
}

func (x *RDAPDomainResponse) GetDomain() *RDAPDomain {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *RDAPDomainResponse) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

var File_proto_domainpb_rdap_proto protoreflect.FileDescriptor

const file_proto_domainpb_rdap_proto_rawDesc = "" +
	"\n" +
	"\x19proto/domainpb/rdap.proto\x12\x06domain\x1a\x1bproto/domainpb/domain.proto\x1a\x15proto/ippb/rdap.proto\"\xf2\x01\n" +
	"\x0eRDAPNameserver\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\x12\x19\n" +
	"\bldh_name\x18\x02 \x01(\tR\aldhName\x12!\n" +
	"\funicode_name\x18\x03 \x01(\tR\vunicodeName\x12&\n" +
	"\x06status\x18\x04 \x03(\x0e2\x0e.ip.RDAPStatusR\x06status\x12\x14\n" +
	"\x05links\x18\x05 \x03(\tR\x05links\x12%\n" +
	"\x0eipv4_addresses\x18\x06 \x03(\tR\ripv4Addresses\x12%\n" +
	"\x0eipv6_addresses\x18\a \x03(\tR\ripv6Addresses\"|\n" +
	"\n" +
	"RDAPDSData\x12\x17\n" +
	"\akey_tag\x18\x01 \x01(\rR\x06keyTag\x12\x1c\n" +
	"\talgorithm\x18\x02 \x01(\rR\talgorithm\x12\x1f\n" +
	"\vdigest_type\x18\x03 \x01(\rR\n" +
	"digestType\x12\x16\n" +
	"\x06digest\x18\x04 \x01(\tR\x06digest\"|\n" +
	"\vRDAPKeyData\x12\x14\n" +
	"\x05flags\x18\x01 \x01(\rR\x05flags\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\rR\bprotocol\x12\x1c\n" +
	"\talgorithm\x18\x03 \x01(\rR\talgorithm\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\tR\tpublicKey\"\x96\x02\n" +
	"\rRDAPSecureDNS\x12+\n" +
	"\x11delegation_signed\x18\x01 \x01(\bR\x10delegationSigned\x12\x1f\n" +
	"\vzone_signed\x18\x02 \x01(\bR\n" +
	"zoneSigned\x128\n" +
	"\x18check_signature_validity\x18\x03 \x01(\bR\x16checkSignatureValidity\x12 \n" +
	"\fmax_sig_life\x18\x04 \x01(\rR\n" +
	"maxSigLife\x12+\n" +
	"\ads_data\x18\x05 \x03(\v2\x12.domain.RDAPDSDataR\x06dsData\x12.\n" +
	"\bkey_data\x18\x06 \x03(\v2\x13.domain.RDAPKeyDataR\akeyData\"\xc7\x03\n" +
	"\n" +
	"RDAPDomain\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\x12\x19\n" +
	"\bldh_name\x18\x02 \x01(\tR\aldhName\x12!\n" +
	"\funicode_name\x18\x03 \x01(\tR\vunicodeName\x128\n" +
	"\vnameservers\x18\x04 \x03(\v2\x16.domain.RDAPNameserverR\vnameservers\x124\n" +
	"\n" +
	"secure_dns\x18\x05 \x01(\v2\x15.domain.RDAPSecureDNSR\tsecureDns\x12&\n" +
	"\x06status\x18\x06 \x03(\x0e2\x0e.ip.RDAPStatusR\x06status\x12*\n" +
	"\bentities\x18\a \x03(\v2\x0e.ip.RDAPEntityR\bentities\x12%\n" +
	"\x06events\x18\b \x03(\v2\r.ip.RDAPEventR\x06events\x12\x14\n" +
	"\x05links\x18\t \x03(\tR\x05links\x12\x1f\n" +
	"\vrdap_server\x18\n" +
	" \x01(\tR\n" +
	"rdapServer\x12)\n" +
	"\x10rdap_conformance\x18\v \x03(\tR\x0frdapConformance\x12\x16\n" +
	"\x06port43\x18\f \x01(\tR\x06port43\"[\n" +
	"\x12RDAPDomainResponse\x12*\n" +
	"\x06domain\x18\x01 \x01(\v2\x12.domain.RDAPDomainR\x06domain\x12\x19\n" +
	"\braw_json\x18\x02 \x01(\tR\arawJson2J\n" +
	"\fRDAPResolver\x12:\n" +
	"\fLookupDomain\x12\x0e.domain.Domain\x1a\x1a.domain.RDAPDomainResponseB=Z;github.com/accretional/proto-domain/proto/domainpb;domainpbb\x06proto3"

var (
	file_proto_domainpb_rdap_proto_rawDescOnce sync.Once
	file_proto_domainpb_rdap_proto_rawDescData []byte
)

func file_proto_domainpb_rdap_proto_rawDescGZIP() []byte {
	file_proto_domainpb_rdap_proto_rawDescOnce.Do(func() {
		file_proto_domainpb_rdap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_domainpb_rdap_proto_rawDesc), len(file_proto_domainpb_rdap_proto_rawDesc)))
	})
	return file_proto_domainpb_rdap_proto_rawDescData
}

var file_proto_domainpb_rdap_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_domainpb_rdap_proto_goTypes = []any{
	(*RDAPNameserver)(nil),     // 0: domain.RDAPNameserver
	(*RDAPDSData)(nil),         // 1: domain.RDAPDSData
	(*RDAPKeyData)(nil),        // 2: domain.RDAPKeyData
	(*RDAPSecureDNS)(nil),      // 3: domain.RDAPSecureDNS
	(*RDAPDomain)(nil),         // 4: domain.RDAPDomain
	(*RDAPDomainResponse)(nil), // 5: domain.RDAPDomainResponse
	(ippb.RDAPStatus)(0),       // 6: ip.RDAPStatus
	(*ippb.RDAPEntity)(nil),    // 7: ip.RDAPEntity
	(*ippb.RDAPEvent)(nil),     // 8: ip.RDAPEvent
	(*Domain)(nil),             // 9: domain.Domain
}
var file_proto_domainpb_rdap_proto_depIdxs = []int32{
	6,  // 0: domain.RDAPNameserver.status:type_name -> ip.RDAPStatus
	1,  // 1: domain.RDAPSecureDNS.ds_data:type_name -> domain.RDAPDSData
	2,  // 2: domain.RDAPSecureDNS.key_data:type_name -> domain.RDAPKeyData
	0,  // 3: domain.RDAPDomain.nameservers:type_name -> domain.RDAPNameserver
	3,  // 4: domain.RDAPDomain.secure_dns:type_name -> domain.RDAPSecureDNS
	6,  // 5: domain.RDAPDomain.status:type_name -> ip.RDAPStatus
	7,  // 6: domain.RDAPDomain.entities:type_name -> ip.RDAPEntity
	8,  // 7: domain.RDAPDomain.events:type_name -> ip.RDAPEvent
	4,  // 8: domain.RDAPDomainResponse.domain:type_name -> domain.RDAPDomain
	9,  // 9: domain.RDAPResolver.LookupDomain:input_type -> domain.Domain
	5,  // 10: domain.RDAPResolver.LookupDomain:output_type -> domain.RDAPDomainResponse
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_domainpb_rdap_proto_init() }
func file_proto_domainpb_rdap_proto_init() {
	if File_proto_domainpb_rdap_proto != nil {
		return
	}
	file_proto_domainpb_domain_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_domainpb_rdap_proto_rawDesc), len(file_proto_domainpb_rdap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_domainpb_rdap_proto_goTypes,
		DependencyIndexes: file_proto_domainpb_rdap_proto_depIdxs,
		MessageInfos:      file_proto_domainpb_rdap_proto_msgTypes,
	}.Build()
	File_proto_domainpb_rdap_proto = out.File
	file_proto_domainpb_rdap_proto_goTypes = nil
	file_proto_domainpb_rdap_proto_depIdxs = nil
}
