// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/domainpb/rdap.proto

package domainpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RDAPResolver_LookupDomain_FullMethodName = "/domain.RDAPResolver/LookupDomain"
)

// RDAPResolverClient is the client API for RDAPResolver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RDAPResolver performs RDAP registration lookups for domain names.
// It uses the IANA bootstrap registry (RFC 7484) to route each query
// to the correct registry operator.
type RDAPResolverClient interface {
	// LookupDomain queries the RDAP registry for a domain name.
	// The TLD is used to route the query via the IANA bootstrap file.
	LookupDomain(ctx context.Context, in *Domain, opts ...grpc.CallOption) (*RDAPDomainResponse, error)
}

type rDAPResolverClient struct {
	cc grpc.ClientConnInterface
}

func NewRDAPResolverClient(cc grpc.ClientConnInterface) RDAPResolverClient {
	return &rDAPResolverClient{cc}
}

func (c *rDAPResolverClient) LookupDomain(ctx context.Context, in *Domain, opts ...grpc.CallOption) (*RDAPDomainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RDAPDomainResponse)
	err := c.cc.Invoke(ctx, RDAPResolver_LookupDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RDAPResolverServer is the server API for RDAPResolver service.
// All implementations must embed UnimplementedRDAPResolverServer
// for forward compatibility.
//
// RDAPResolver performs RDAP registration lookups for domain names.
// It uses the IANA bootstrap registry (RFC 7484) to route each query
// to the correct registry operator.
type RDAPResolverServer interface {
	// LookupDomain queries the RDAP registry for a domain name.
	// The TLD is used to route the query via the IANA bootstrap file.
	LookupDomain(context.Context, *Domain) (*RDAPDomainResponse, error)
	mustEmbedUnimplementedRDAPResolverServer()
}

// UnimplementedRDAPResolverServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRDAPResolverServer struct{}

func (UnimplementedRDAPResolverServer) LookupDomain(context.Context, *Domain) (*RDAPDomainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupDomain not implemented")
}
func (UnimplementedRDAPResolverServer) mustEmbedUnimplementedRDAPResolverServer() {}
func (UnimplementedRDAPResolverServer) testEmbeddedByValue()                      {}

// UnsafeRDAPResolverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RDAPResolverServer will
// result in compilation errors.
type UnsafeRDAPResolverServer interface {
	mustEmbedUnimplementedRDAPResolverServer()
}

func RegisterRDAPResolverServer(s grpc.ServiceRegistrar, srv RDAPResolverServer) {
	// If the following call panics, it indicates UnimplementedRDAPResolverServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RDAPResolver_ServiceDesc, srv)
}

func _RDAPResolver_LookupDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Domain)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RDAPResolverServer).LookupDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RDAPResolver_LookupDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RDAPResolverServer).LookupDomain(ctx, req.(*Domain))
	}
	return interceptor(ctx, in, info, handler)
}

// RDAPResolver_ServiceDesc is the grpc.ServiceDesc for RDAPResolver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RDAPResolver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "domain.RDAPResolver",
	HandlerType: (*RDAPResolverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LookupDomain",
			Handler:    _RDAPResolver_LookupDomain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/domainpb/rdap.proto",
}
