// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/domainpb/resolver.proto

package domainpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_domainpb_resolver_proto protoreflect.FileDescriptor

const file_proto_domainpb_resolver_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/domainpb/resolver.proto\x12\x06domain\x1a\x1bproto/domainpb/domain.proto\x1a\x1fproto/domainpb/dns_record.proto2@\n" +
	"\bResolver\x124\n" +
	"\rGetDNSRecords\x12\x0e.domain.Domain\x1a\x11.domain.DNSRecord0\x01B=Z;github.com/accretional/proto-domain/proto/domainpb;domainpbb\x06proto3"

var file_proto_domainpb_resolver_proto_goTypes = []any{
	(*Domain)(nil),    // 0: domain.Domain
	(*DNSRecord)(nil), // 1: domain.DNSRecord
}
var file_proto_domainpb_resolver_proto_depIdxs = []int32{
	0, // 0: domain.Resolver.GetDNSRecords:input_type -> domain.Domain
	1, // 1: domain.Resolver.GetDNSRecords:output_type -> domain.DNSRecord
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_domainpb_resolver_proto_init() }
func file_proto_domainpb_resolver_proto_init() {
	if File_proto_domainpb_resolver_proto != nil {
		return
	}
	file_proto_domainpb_domain_proto_init()
	file_proto_domainpb_dns_record_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_domainpb_resolver_proto_rawDesc), len(file_proto_domainpb_resolver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_domainpb_resolver_proto_goTypes,
		DependencyIndexes: file_proto_domainpb_resolver_proto_depIdxs,
	}.Build()
	File_proto_domainpb_resolver_proto = out.File
	file_proto_domainpb_resolver_proto_goTypes = nil
	file_proto_domainpb_resolver_proto_depIdxs = nil
}
