// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: proto/domainpb/resolver.proto

package domainpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Resolver_GetDNSRecords_FullMethodName = "/domain.Resolver/GetDNSRecords"
)

// ResolverClient is the client API for Resolver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Resolver answers DNS queries against the host's resolver configuration.
type ResolverClient interface {
	// GetDNSRecords streams every DNSRecord the local resolver returns for
	// the supplied Domain. Record types that yield zero results are omitted
	// from the stream rather than emitting an empty placeholder.
	GetDNSRecords(ctx context.Context, in *Domain, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DNSRecord], error)
}

type resolverClient struct {
	cc grpc.ClientConnInterface
}

func NewResolverClient(cc grpc.ClientConnInterface) ResolverClient {
	return &resolverClient{cc}
}

func (c *resolverClient) GetDNSRecords(ctx context.Context, in *Domain, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DNSRecord], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Resolver_ServiceDesc.Streams[0], Resolver_GetDNSRecords_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Domain, DNSRecord]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Resolver_GetDNSRecordsClient = grpc.ServerStreamingClient[DNSRecord]

// ResolverServer is the server API for Resolver service.
// All implementations must embed UnimplementedResolverServer
// for forward compatibility.
//
// Resolver answers DNS queries against the host's resolver configuration.
type ResolverServer interface {
	// GetDNSRecords streams every DNSRecord the local resolver returns for
	// the supplied Domain. Record types that yield zero results are omitted
	// from the stream rather than emitting an empty placeholder.
	GetDNSRecords(*Domain, grpc.ServerStreamingServer[DNSRecord]) error
	mustEmbedUnimplementedResolverServer()
}

// UnimplementedResolverServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResolverServer struct{}

func (UnimplementedResolverServer) GetDNSRecords(*Domain, grpc.ServerStreamingServer[DNSRecord]) error {
	return status.Errorf(codes.Unimplemented, "method GetDNSRecords not implemented")
}
func (UnimplementedResolverServer) mustEmbedUnimplementedResolverServer() {}
func (UnimplementedResolverServer) testEmbeddedByValue()                  {}

// UnsafeResolverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResolverServer will
// result in compilation errors.
type UnsafeResolverServer interface {
	mustEmbedUnimplementedResolverServer()
}

func RegisterResolverServer(s grpc.ServiceRegistrar, srv ResolverServer) {
	// If the following call pancis, it indicates UnimplementedResolverServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Resolver_ServiceDesc, srv)
}

func _Resolver_GetDNSRecords_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Domain)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ResolverServer).GetDNSRecords(m, &grpc.GenericServerStream[Domain, DNSRecord]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Resolver_GetDNSRecordsServer = grpc.ServerStreamingServer[DNSRecord]

// Resolver_ServiceDesc is the grpc.ServiceDesc for Resolver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Resolver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "domain.Resolver",
	HandlerType: (*ResolverServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetDNSRecords",
			Handler:       _Resolver_GetDNSRecords_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/domainpb/resolver.proto",
}
