// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/domainpb/url.proto

package domainpb

import (
	ippb "github.com/accretional/proto-ip/proto/ippb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// helpful: https://en.wikipedia.org/wiki/List_of_URI_schemes
type URIScheme int32

const (
	URIScheme_SCHEME_UNKNOWN URIScheme = 0
	URIScheme_SCHEME_HTTP    URIScheme = 1
	URIScheme_SCHEME_HTTPS   URIScheme = 2
	URIScheme_SCHEME_FILE    URIScheme = 3
	URIScheme_SCHEME_FTP     URIScheme = 4
	URIScheme_SCHEME_MAILTO  URIScheme = 5
	URIScheme_SCHEME_TEL     URIScheme = 6
	URIScheme_SCHEME_IMAP    URIScheme = 7
	URIScheme_SCHEME_IRC     URIScheme = 8
	URIScheme_SCHEME_WS      URIScheme = 9
	URIScheme_SCHEME_WSS     URIScheme = 10 // Keep these protocol-level and non-proprietary
)

// Enum value maps for URIScheme.
var (
	URIScheme_name = map[int32]string{
		0:  "SCHEME_UNKNOWN",
		1:  "SCHEME_HTTP",
		2:  "SCHEME_HTTPS",
		3:  "SCHEME_FILE",
		4:  "SCHEME_FTP",
		5:  "SCHEME_MAILTO",
		6:  "SCHEME_TEL",
		7:  "SCHEME_IMAP",
		8:  "SCHEME_IRC",
		9:  "SCHEME_WS",
		10: "SCHEME_WSS",
	}
	URIScheme_value = map[string]int32{
		"SCHEME_UNKNOWN": 0,
		"SCHEME_HTTP":    1,
		"SCHEME_HTTPS":   2,
		"SCHEME_FILE":    3,
		"SCHEME_FTP":     4,
		"SCHEME_MAILTO":  5,
		"SCHEME_TEL":     6,
		"SCHEME_IMAP":    7,
		"SCHEME_IRC":     8,
		"SCHEME_WS":      9,
		"SCHEME_WSS":     10,
	}
)

func (x URIScheme) Enum() *URIScheme {
	p := new(URIScheme)
	*p = x
	return p
}

func (x URIScheme) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (URIScheme) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_domainpb_url_proto_enumTypes[0].Descriptor()
}

func (URIScheme) Type() protoreflect.EnumType {
	return &file_proto_domainpb_url_proto_enumTypes[0]
}

func (x URIScheme) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use URIScheme.Descriptor instead.
func (URIScheme) EnumDescriptor() ([]byte, []int) {
	return file_proto_domainpb_url_proto_rawDescGZIP(), []int{0}
}

type Scheme struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Format:
	//
	//	*Scheme_Protocol
	//	*Scheme_Custom
	Format        isScheme_Format `protobuf_oneof:"format"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scheme) Reset() {
	*x = Scheme{}
	mi := &file_proto_domainpb_url_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scheme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scheme) ProtoMessage() {}

func (x *Scheme) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domainpb_url_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scheme.ProtoReflect.Descriptor instead.
func (*Scheme) Descriptor() ([]byte, []int) {
	return file_proto_domainpb_url_proto_rawDescGZIP(), []int{0}
}

func (x *Scheme) GetFormat() isScheme_Format {
	if x != nil {
		return x.Format
	}
	return nil
}

func (x *Scheme) GetProtocol() URIScheme {
	if x != nil {
		if x, ok := x.Format.(*Scheme_Protocol); ok {
			return x.Protocol
		}
	}
	return URIScheme_SCHEME_UNKNOWN
}

func (x *Scheme) GetCustom() string {
	if x != nil {
		if x, ok := x.Format.(*Scheme_Custom); ok {
			return x.Custom
		}
	}
	return ""
}

type isScheme_Format interface {
	isScheme_Format()
}

type Scheme_Protocol struct {
	Protocol URIScheme `protobuf:"varint,1,opt,name=protocol,proto3,enum=domain.URIScheme,oneof"`
}

type Scheme_Custom struct {
	Custom string `protobuf:"bytes,2,opt,name=custom,proto3,oneof"`
}

func (*Scheme_Protocol) isScheme_Format() {}

func (*Scheme_Custom) isScheme_Format() {}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_proto_domainpb_url_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domainpb_url_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_proto_domainpb_url_proto_rawDescGZIP(), []int{1}
}

func (x *UserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type Authority struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	UserInfo *UserInfo              `protobuf:"bytes,1,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	// Types that are valid to be assigned to Host:
	//
	//	*Authority_Hostname
	//	*Authority_Ip
	Host isAuthority_Host `protobuf_oneof:"host"`
	// leave 0 if unspecified
	Port          int32 `protobuf:"zigzag32,5,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Authority) Reset() {
	*x = Authority{}
	mi := &file_proto_domainpb_url_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authority) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authority) ProtoMessage() {}

func (x *Authority) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domainpb_url_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authority.ProtoReflect.Descriptor instead.
func (*Authority) Descriptor() ([]byte, []int) {
	return file_proto_domainpb_url_proto_rawDescGZIP(), []int{2}
}

func (x *Authority) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

func (x *Authority) GetHost() isAuthority_Host {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *Authority) GetHostname() *Domain {
	if x != nil {
		if x, ok := x.Host.(*Authority_Hostname); ok {
			return x.Hostname
		}
	}
	return nil
}

func (x *Authority) GetIp() *ippb.IP {
	if x != nil {
		if x, ok := x.Host.(*Authority_Ip); ok {
			return x.Ip
		}
	}
	return nil
}

func (x *Authority) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type isAuthority_Host interface {
	isAuthority_Host()
}

type Authority_Hostname struct {
	Hostname *Domain `protobuf:"bytes,2,opt,name=hostname,proto3,oneof"`
}

type Authority_Ip struct {
	Ip *ippb.IP `protobuf:"bytes,3,opt,name=ip,proto3,oneof"`
}

func (*Authority_Hostname) isAuthority_Host() {}

func (*Authority_Ip) isAuthority_Host() {}

// TODO
type QueryParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParam) Reset() {
	*x = QueryParam{}
	mi := &file_proto_domainpb_url_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParam) ProtoMessage() {}

func (x *QueryParam) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domainpb_url_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParam.ProtoReflect.Descriptor instead.
func (*QueryParam) Descriptor() ([]byte, []int) {
	return file_proto_domainpb_url_proto_rawDescGZIP(), []int{3}
}

func (x *QueryParam) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *QueryParam) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type URL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scheme        *Scheme                `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Authority     *Authority             `protobuf:"bytes,2,opt,name=authority,proto3" json:"authority,omitempty"`
	Subpaths      []string               `protobuf:"bytes,3,rep,name=subpaths,proto3" json:"subpaths,omitempty"`
	QueryParams   []*QueryParam          `protobuf:"bytes,4,rep,name=query_params,json=queryParams,proto3" json:"query_params,omitempty"`
	Fragments     []string               `protobuf:"bytes,5,rep,name=fragments,proto3" json:"fragments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URL) Reset() {
	*x = URL{}
	mi := &file_proto_domainpb_url_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URL) ProtoMessage() {}

func (x *URL) ProtoReflect() protoreflect.Message {
	mi := &file_proto_domainpb_url_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URL.ProtoReflect.Descriptor instead.
func (*URL) Descriptor() ([]byte, []int) {
	return file_proto_domainpb_url_proto_rawDescGZIP(), []int{4}
}

func (x *URL) GetScheme() *Scheme {
	if x != nil {
		return x.Scheme
	}
	return nil
}

func (x *URL) GetAuthority() *Authority {
	if x != nil {
		return x.Authority
	}
	return nil
}

func (x *URL) GetSubpaths() []string {
	if x != nil {
		return x.Subpaths
	}
	return nil
}

func (x *URL) GetQueryParams() []*QueryParam {
	if x != nil {
		return x.QueryParams
	}
	return nil
}

func (x *URL) GetFragments() []string {
	if x != nil {
		return x.Fragments
	}
	return nil
}

var File_proto_domainpb_url_proto protoreflect.FileDescriptor

const file_proto_domainpb_url_proto_rawDesc = "" +
	"\n" +
	"\x18proto/domainpb/url.proto\x12\x06domain\x1a\x1bproto/domainpb/domain.proto\x1a\x13proto/ippb/ip.proto\"]\n" +
	"\x06Scheme\x12/\n" +
	"\bprotocol\x18\x01 \x01(\x0e2\x11.domain.URISchemeH\x00R\bprotocol\x12\x18\n" +
	"\x06custom\x18\x02 \x01(\tH\x00R\x06customB\b\n" +
	"\x06format\"&\n" +
	"\bUserInfo\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"\x9e\x01\n" +
	"\tAuthority\x12-\n" +
	"\tuser_info\x18\x01 \x01(\v2\x10.domain.UserInfoR\buserInfo\x12,\n" +
	"\bhostname\x18\x02 \x01(\v2\x0e.domain.DomainH\x00R\bhostname\x12\x18\n" +
	"\x02ip\x18\x03 \x01(\v2\x06.ip.IPH\x00R\x02ip\x12\x12\n" +
	"\x04port\x18\x05 \x01(\x11R\x04portB\x06\n" +
	"\x04host\"4\n" +
	"\n" +
	"QueryParam\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xcf\x01\n" +
	"\x03URL\x12&\n" +
	"\x06scheme\x18\x01 \x01(\v2\x0e.domain.SchemeR\x06scheme\x12/\n" +
	"\tauthority\x18\x02 \x01(\v2\x11.domain.AuthorityR\tauthority\x12\x1a\n" +
	"\bsubpaths\x18\x03 \x03(\tR\bsubpaths\x125\n" +
	"\fquery_params\x18\x04 \x03(\v2\x12.domain.QueryParamR\vqueryParams\x12\x1c\n" +
	"\tfragments\x18\x05 \x03(\tR\tfragments*\xc6\x01\n" +
	"\tURIScheme\x12\x12\n" +
	"\x0eSCHEME_UNKNOWN\x10\x00\x12\x0f\n" +
	"\vSCHEME_HTTP\x10\x01\x12\x10\n" +
	"\fSCHEME_HTTPS\x10\x02\x12\x0f\n" +
	"\vSCHEME_FILE\x10\x03\x12\x0e\n" +
	"\n" +
	"SCHEME_FTP\x10\x04\x12\x11\n" +
	"\rSCHEME_MAILTO\x10\x05\x12\x0e\n" +
	"\n" +
	"SCHEME_TEL\x10\x06\x12\x0f\n" +
	"\vSCHEME_IMAP\x10\a\x12\x0e\n" +
	"\n" +
	"SCHEME_IRC\x10\b\x12\r\n" +
	"\tSCHEME_WS\x10\t\x12\x0e\n" +
	"\n" +
	"SCHEME_WSS\x10\n" +
	"B=Z;github.com/accretional/proto-domain/proto/domainpb;domainpbb\x06proto3"

var (
	file_proto_domainpb_url_proto_rawDescOnce sync.Once
	file_proto_domainpb_url_proto_rawDescData []byte
)

func file_proto_domainpb_url_proto_rawDescGZIP() []byte {
	file_proto_domainpb_url_proto_rawDescOnce.Do(func() {
		file_proto_domainpb_url_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_domainpb_url_proto_rawDesc), len(file_proto_domainpb_url_proto_rawDesc)))
	})
	return file_proto_domainpb_url_proto_rawDescData
}

var file_proto_domainpb_url_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_domainpb_url_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_domainpb_url_proto_goTypes = []any{
	(URIScheme)(0),     // 0: domain.URIScheme
	(*Scheme)(nil),     // 1: domain.Scheme
	(*UserInfo)(nil),   // 2: domain.UserInfo
	(*Authority)(nil),  // 3: domain.Authority
	(*QueryParam)(nil), // 4: domain.QueryParam
	(*URL)(nil),        // 5: domain.URL
	(*Domain)(nil),     // 6: domain.Domain
	(*ippb.IP)(nil),    // 7: ip.IP
}
var file_proto_domainpb_url_proto_depIdxs = []int32{
	0, // 0: domain.Scheme.protocol:type_name -> domain.URIScheme
	2, // 1: domain.Authority.user_info:type_name -> domain.UserInfo
	6, // 2: domain.Authority.hostname:type_name -> domain.Domain
	7, // 3: domain.Authority.ip:type_name -> ip.IP
	1, // 4: domain.URL.scheme:type_name -> domain.Scheme
	3, // 5: domain.URL.authority:type_name -> domain.Authority
	4, // 6: domain.URL.query_params:type_name -> domain.QueryParam
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_domainpb_url_proto_init() }
func file_proto_domainpb_url_proto_init() {
	if File_proto_domainpb_url_proto != nil {
		return
	}
	file_proto_domainpb_domain_proto_init()
	file_proto_domainpb_url_proto_msgTypes[0].OneofWrappers = []any{
		(*Scheme_Protocol)(nil),
		(*Scheme_Custom)(nil),
	}
	file_proto_domainpb_url_proto_msgTypes[2].OneofWrappers = []any{
		(*Authority_Hostname)(nil),
		(*Authority_Ip)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_domainpb_url_proto_rawDesc), len(file_proto_domainpb_url_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_domainpb_url_proto_goTypes,
		DependencyIndexes: file_proto_domainpb_url_proto_depIdxs,
		EnumInfos:         file_proto_domainpb_url_proto_enumTypes,
		MessageInfos:      file_proto_domainpb_url_proto_msgTypes,
	}.Build()
	File_proto_domainpb_url_proto = out.File
	file_proto_domainpb_url_proto_goTypes = nil
	file_proto_domainpb_url_proto_depIdxs = nil
}
